'use client'

import { useEffect, useState } from 'react'

/**
 * For Creators, mobile layout — ported from the "GUAPD For Creators - Mobile"
 * export.
 *
 * Markup is generated by scripts/creators-mobile-convert-from-export.py — edit
 * the converter and re-run it, not the JSX below, or the next port silently
 * drops the change.
 *
 * This is a SEPARATE LAYOUT, not the desktop page reflowed. The two exports
 * share exactly one class name between them, so there was no set of breakpoint
 * overrides that could turn one into the other.
 *
 * Both are in the DOM and creators-mobile.css picks one at 820px. `display:
 * none` also removes the hidden layout from the accessibility tree, so a screen
 * reader is never read both copies. The trade is page weight, taken knowingly:
 * the alternative — choosing in JavaScript — either flashes the wrong layout or
 * forces the server to guess the viewport.
 *
 * Every heading here is h2 or lower. The desktop layout owns the page's single
 * h1, and since both are in the DOM a second one would give the page two.
 */
export default function CreatorsMobileClient() {
  // The two accordion rows. 0 means none is open, which is the state the export
  // starts in; clicking the open one closes it.
  const [openRow, setOpenRow] = useState(0)

  useEffect(() => {
    // The export's reveal convention, same as the desktop port: .sr becomes
    // .sr-in once the element has been seen. Elements are revealed rather than
    // hidden if IntersectionObserver is missing, so nothing can end up stuck
    // invisible.
    const nodes = Array.from(document.querySelectorAll('.creators-mobile .sr'))
    if (!nodes.length) return
    if (typeof IntersectionObserver === 'undefined') {
      nodes.forEach((n) => n.classList.add('sr-in'))
      return
    }
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            e.target.classList.add('sr-in')
            io.unobserve(e.target)
          }
        })
      },
      { rootMargin: '0px 0px -12% 0px', threshold: 0.05 },
    )
    nodes.forEach((n) => io.observe(n))
    return () => io.disconnect()
  }, [])

  return (
    <div className="creators-mobile">
      <div className="mobile-frame">
      <div style={{fontFamily: 'var(--font-ui)', color: 'var(--ink)', position: 'relative', overflowX: 'hidden', background: '#fff'}}>

        {/* NAV */}
        <div style={{position: 'sticky', top: '0', zIndex: '100'}}>
    
        </div>

        {/* HERO */}
        <section className="hr" style={{padding: '56px 24px 32px', textAlign: 'center'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}><span style={{width: '5px', height: '5px', borderRadius: '50%', background: 'var(--ink)', flexShrink: '0'}}></span>Built for creators</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '30px', lineHeight: '1.2', margin: '20px 0 0', color: 'var(--ink)'}}>The operating system for <span className="opit">creator collabs.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '16px auto 0', maxWidth: '30ch'}}>Keep every opportunity, deliverable and payment in one place.</p>
        </section>
        <div style={{padding: '0 24px', marginTop: '32px', marginBottom: '56px'}}><img src="/creators-mobile/4e8cae69.webp" alt="guapd dashboard showing total earnings, overview, deals, and upcoming deliverables" style={{width: '100%', aspectRatio: '1060/1484', objectFit: 'cover', display: 'block', borderRadius: '28px'}} decoding="async" loading="lazy" /></div>

        {/* DEALS */}
        <section id="top" className="hr" style={{padding: '48px 24px 44px', marginTop: '28px', background: 'var(--ink)', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}>For creators</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '27px', lineHeight: '1.2', margin: '18px 0 0', color: '#fff'}}>Every deal you're offered, <span className="opit" style={{color: 'var(--neon)'}}>all tracked.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.6', color: '#B8BAB0', margin: '14px 0 0'}}>Every offer, deliverable and payment, in one place instead of scattered across DMs and spreadsheets.</p>

          <div style={{marginTop: '40px'}}>
            <span style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '12px', color: '#B8BAB0', textTransform: 'uppercase', letterSpacing: '.06em'}}>Beyond the basics</span>
            <div style={{display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '14px'}}>
              <div style={{display: 'flex', alignItems: 'center', gap: '14px', padding: '16px', border: '1px solid rgba(255,255,255,.18)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', flexShrink: '0'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3v18h18" /><path d="M7 15l4-4 3 3 5-6" /></svg></span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13.5px', color: '#fff'}}>Performance analytics</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: '#9EA096', marginTop: '3px'}}>See what's working, deal by deal</div></div></div>
              <div style={{display: 'flex', alignItems: 'center', gap: '14px', padding: '16px', border: '1px solid rgba(255,255,255,.18)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', flexShrink: '0'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" /></svg></span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13.5px', color: '#fff'}}>Your own storefront</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: '#9EA096', marginTop: '3px'}}>Rates and portfolio, one link</div></div></div>
              <div style={{display: 'flex', alignItems: 'center', gap: '14px', padding: '16px', border: '1px solid rgba(255,255,255,.18)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', flexShrink: '0'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13.5px', color: '#fff'}}>Never chase payments</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: '#9EA096', marginTop: '3px'}}>Automatic follow-ups on brands</div></div></div>
              <div style={{display: 'flex', alignItems: 'center', gap: '14px', padding: '16px', border: '1px solid rgba(255,255,255,.18)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', flexShrink: '0'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" /><path d="M3 10h18" /><path d="M8 2v4" /><path d="M16 2v4" /></svg></span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13.5px', color: '#fff'}}>Never miss a deadline</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: '#9EA096', marginTop: '3px'}}>Every deal, one calendar</div></div></div>
            </div>
          </div>
        </section>

        {/* VALUE TICKER */}
        <section className="hr" style={{padding: '24px 0'}}>
          <div style={{position: 'relative', overflow: 'hidden', WebkitMaskImage: 'linear-gradient(90deg,transparent,#000 9%,#000 91%,transparent)', maskImage: 'linear-gradient(90deg,transparent,#000 9%,#000 91%,transparent)'}}>
            <div style={{display: 'flex', width: 'max-content', gap: '10px', animation: 'mqMove 26s linear infinite', paddingRight: '10px'}}>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#7FA8E8'}}></span>locked terms</span>
              <span style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)'}}>·</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#8FD4A8'}}></span>on-time payouts</span>
              <span style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)'}}>·</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#E8B36B'}}></span>full paper trail</span>
              <span style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)'}}>·</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#C9A0E0'}}></span>no chasing brands</span>
              <span style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)'}}>·</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#7FA8E8'}}></span>locked terms</span>
              <span aria-hidden="true" style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)'}}>·</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#8FD4A8'}}></span>on-time payouts</span>
              <span aria-hidden="true" style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: 'var(--ink-soft)'}}>·</span>
            </div>
          </div>
        </section>

        {/* EARNINGS */}
        <section className="hr" style={{padding: '56px 24px 40px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>For creators</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '26px', lineHeight: '1.2', margin: '20px 0 0', color: 'var(--ink)'}}>Watch your earnings <span className="opit">add up.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '16px 0 0', maxWidth: '30ch'}}>Every deal, past and present, rolls into one earnings view, so you always know what you've made.</p>
        </section>
        <div style={{padding: '0 24px'}}><img src="/creators-mobile/a777545a.webp" alt="guapd payment overview showing payment received, timeline, and payment details" style={{width: '100%', aspectRatio: '948/1330', objectFit: 'cover', objectPosition: 'center bottom', display: 'block', borderRadius: '16px'}} decoding="async" loading="lazy" /></div>
        <div style={{padding: '38px 24px 36px'}}>
          <div style={{borderTop: '1px solid var(--hairline)'}}>
            <div onClick={() => setOpenRow(openRow === 1 ? 0 : 1)} style={{display: 'flex', alignItems: 'center', gap: '12px', padding: '16px 0', cursor: 'pointer'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0'}}><rect x="2" y="5" width="20" height="14" rx="2" /><line x1="2" y1="10" x2="22" y2="10" /></svg><span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '14px', color: 'var(--ink)', flex: '1'}}>Money tracked, paid on time</span><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--ink-faint)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0', transform: '{row1Arrow}', transition: 'transform .2s'}}><path d="M6 9l6 6 6-6" /></svg></div>
            {(openRow === 1) && (<><p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.6', color: 'var(--ink-2)', margin: '0 0 16px', paddingLeft: '32px'}}>Every payment is followed from offer to payout, so you always know where it stands.</p></>)}
          </div>
          <div style={{borderTop: '1px solid var(--hairline)', borderBottom: '1px solid var(--hairline)'}}>
            <div onClick={() => setOpenRow(openRow === 2 ? 0 : 2)} style={{display: 'flex', alignItems: 'center', gap: '12px', padding: '16px 0', cursor: 'pointer'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0'}}><path d="M14 3v4a1 1 0 0 0 1 1h4" /><path d="M5 21V5a2 2 0 0 1 2-2h7l5 5v13a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2Z" /></svg><span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '14px', color: 'var(--ink)', flex: '1'}}>Statements and invoices</span><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--ink-faint)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0', transform: '{row2Arrow}', transition: 'transform .2s'}}><path d="M6 9l6 6 6-6" /></svg></div>
            {(openRow === 2) && (<><p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.6', color: 'var(--ink-2)', margin: '0 0 16px', paddingLeft: '32px'}}>Download a clean record any time, ready for accounting or tax season.</p></>)}
          </div>
        </div>

        {/* HOW IT WORKS */}
        <section id="how" className="hr" style={{padding: '56px 24px', background: 'var(--ink)', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}>How it works</span>
          <div style={{marginTop: '20px', paddingTop: '24px', borderTop: '1px solid rgba(255,255,255,.16)', display: 'flex', gap: '16px'}}><span className="oavatar" style={{width: '26px', height: '26px', background: 'var(--neon)', color: 'var(--ink)', fontSize: '10.5px', flexShrink: '0'}}>01</span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Every deal, one place</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#B8BAB0', margin: '8px 0 0'}}>No more offers buried in Instagram DMs. Every brand brief arrives as a structured card.</p></div></div>
          <div style={{paddingTop: '24px', marginTop: '24px', borderTop: '1px solid rgba(255,255,255,.16)', display: 'flex', gap: '16px'}}><span className="oavatar" style={{width: '26px', height: '26px', background: 'var(--neon)', color: 'var(--ink)', fontSize: '10.5px', flexShrink: '0'}}>02</span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Upload and get approved</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#B8BAB0', margin: '8px 0 0'}}>Track revision requests and see exactly how many rounds are left.</p></div></div>
          <div style={{paddingTop: '24px', marginTop: '24px', borderTop: '1px solid rgba(255,255,255,.16)', display: 'flex', gap: '16px'}}><span className="oavatar" style={{width: '26px', height: '26px', background: 'var(--neon)', color: 'var(--ink)', fontSize: '10.5px', flexShrink: '0'}}>03</span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Know when you get paid</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#B8BAB0', margin: '8px 0 0'}}>Watch payment move from link sent to paid in real time. No chasing.</p></div></div>
        </section>

        {/* WHY CREATORS SWITCH */}
        <section className="hr" style={{padding: '56px 24px 32px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Why creators switch</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.22', fontSize: '24px', margin: '20px 0 0', color: 'var(--ink)'}}>Everything DMs can't <span className="opit">give you.</span></h2>
        </section>
        <div style={{padding: '0 24px'}}><img src="/creators-mobile/ecc6107b.webp" alt="Dashboard showing active collaborations" style={{width: '100%', aspectRatio: '4/3', display: 'block'}} decoding="async" loading="lazy" /></div>
        <div style={{padding: '22px 24px 36px'}}>
          <div style={{borderRadius: '14px', overflow: 'hidden', border: '1px solid var(--hairline)'}}>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', background: '#fff'}}>
              <span style={{padding: '15px 16px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '10.5px', letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--ink)'}}>What you get</span>
              <span style={{padding: '15px 8px', textAlign: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)', borderLeft: '1px solid var(--hairline)'}}>Guapd</span>
              <span style={{padding: '15px 8px', textAlign: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)', borderLeft: '1px solid var(--hairline)'}}>DMs</span>
            </div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>Offers in one place</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#C7C9C0" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg></span></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>Written, locked terms</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#C7C9C0" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg></span></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>Revision tracking</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#C7C9C0" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg></span></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>Money released on approval</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#C7C9C0" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg></span></div>
          </div>
        </div>

        {/* EVERYTHING YOU NEED */}
        <section className="hr" style={{padding: '56px 24px', background: 'var(--ink)', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Everything you need</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '23px', margin: '20px 0 0', color: '#fff'}}>Everything you <span className="opit" style={{color: 'var(--neon)'}}>need</span></h2>
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginTop: '32px'}}>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M22 12h-6l-2 3h-4l-2-3H2" /><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Deal inbox</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Structured, easy to answer</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M7 11V7a5 5 0 0 1 10 0v4" /><rect x="3" y="11" width="18" height="10" rx="2" /><path d="m9 16 2 2 4-4" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Accept or counter</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>One tap, or with a reason</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l1.5-5h15L21 9" /><path d="M3 9v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9" /><path d="M3 9h18" /><path d="M9 21v-6h6v6" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Shopfront</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Rates and past work, one link</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="5" width="20" height="14" rx="2" /><line x1="2" y1="10" x2="22" y2="10" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Payment status</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Pending to paid, live</div></div>
          </div>
        </section>

        {/* BUILT FOR TRUST */}
        <section id="privacySec" className="hr" style={{padding: '56px 24px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Built for trust</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '23px', margin: '20px 0 0', color: 'var(--ink)'}}>Your deals, <span className="opit">protected.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.6', color: 'var(--ink-2)', margin: '14px 0 0'}}>Every collaboration on guapd is backed by a written contract and a payment that's tracked from day one.</p>
          <div style={{display: 'flex', flexDirection: 'column', gap: '12px', marginTop: '26px'}}>
            <div style={{display: 'flex', gap: '16px', alignItems: 'center', padding: '20px', border: '1px solid var(--hairline)', borderRadius: '16px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: '#E9F7F0', flexShrink: '0'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.6"><path d="M12 2 4 6v6c0 5 4 8 8 10 4-2 8-5 8-10V6z" /></svg></span><div style={{flex: '1'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', color: 'var(--ink)'}}>Written contracts, every time</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', color: 'var(--ink-2)', marginTop: '3px'}}>Terms locked before work starts</div></div></div>
            <div style={{display: 'flex', gap: '16px', alignItems: 'center', padding: '20px', border: '1px solid var(--hairline)', borderRadius: '16px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: '#E7F1FC', flexShrink: '0'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.6"><rect x="3" y="6" width="18" height="14" rx="2" /><line x1="3" y1="11" x2="21" y2="11" /></svg></span><div style={{flex: '1'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', color: 'var(--ink)'}}>Payment status, always visible</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', color: 'var(--ink-2)', marginTop: '3px'}}>No chasing, no vague replies</div></div></div>
            <div style={{display: 'flex', gap: '16px', alignItems: 'center', padding: '20px', border: '1px solid var(--hairline)', borderRadius: '16px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: '#FCF6E4', flexShrink: '0'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.6"><path d="M20 6 9 17l-5-5" /></svg></span><div style={{flex: '1'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', color: 'var(--ink)'}}>Approvals on record</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', color: 'var(--ink-2)', marginTop: '3px'}}>Scope stays what was agreed</div></div></div>
          </div>
        </section>

        {/* ONE DASHBOARD SHOWCASE */}
        <section className="hr" style={{padding: '52px 24px 0', textAlign: 'center'}}>
          <span style={{width: '6px', height: '6px', borderRadius: '50%', background: 'var(--neon-deep)', display: 'inline-block', marginBottom: '18px'}}></span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '28px', lineHeight: '1.2', margin: '0', color: 'var(--ink)'}}>Run your creator business from <span className="opit">one place.</span></h2>
        </section>
        <div style={{padding: '20px 24px 36px'}}><img src="/creators-mobile/a1a47f79.webp" alt="Earnings dashboard showing total earnings and monthly breakdown" style={{width: '100%', aspectRatio: '947/1661', objectFit: 'cover', objectPosition: 'top', display: 'block', borderRadius: '16px'}} decoding="async" loading="lazy" /></div>

        {/* CREATORS WE WORK WITH */}
  

        {/* BRANDS ON GUAPD */}
  

        {/* TESTIMONIALS */}
        <section id="creators" className="hr" style={{padding: '36px 0'}}>
          <div style={{padding: '0 24px'}}>
            <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Testimonials</span>
            <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '23px', margin: '20px 0 0', color: 'var(--ink)'}}>Why creators are making the <span className="opit">switch.</span></h2>
          </div>
          <div className="snap-track" style={{gap: '20px', padding: '0 24px', marginTop: '32px'}}>
            <div style={{scrollSnapAlign: 'start', flex: '0 0 82%', minWidth: '0', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '18px', padding: '28px 24px', display: 'flex', flexDirection: 'column'}}>
              <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: '36px', color: 'var(--ink-faint)', lineHeight: '1'}}>“</span>
              <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.02em', margin: '10px 0 0', color: 'var(--ink)'}}>Written terms, finally</h3>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: 'var(--ink-soft)', margin: '8px 0 0'}}>I have had brands forget what we agreed verbally three times in one campaign.</p>
              <div style={{marginTop: '16px', borderTop: '1px solid var(--hairline)', paddingTop: '14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
                <span style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)'}}>Finance creator</span>
                <span style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: 'var(--ink-faint)'}}>@aisha.fin</span>
              </div>
            </div>
            <div style={{scrollSnapAlign: 'start', flex: '0 0 82%', minWidth: '0', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '18px', padding: '28px 24px', display: 'flex', flexDirection: 'column'}}>
              <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: '36px', color: 'var(--ink-faint)', lineHeight: '1'}}>“</span>
              <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.02em', margin: '10px 0 0', color: 'var(--ink)'}}>No more chasing payment</h3>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: 'var(--ink-soft)', margin: '8px 0 0'}}>If I could see exactly where a payment is, I would sleep better.</p>
              <div style={{marginTop: '16px', borderTop: '1px solid var(--hairline)', paddingTop: '14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
                <span style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)'}}>Tech creator</span>
                <span style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: 'var(--ink-faint)'}}>@rohan.tech</span>
              </div>
            </div>
            <div style={{scrollSnapAlign: 'start', flex: '0 0 82%', minWidth: '0', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '18px', padding: '28px 24px', display: 'flex', flexDirection: 'column'}}>
              <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: '36px', color: 'var(--ink-faint)', lineHeight: '1'}}>“</span>
              <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.02em', margin: '10px 0 0', color: 'var(--ink)'}}>An actual inbox for deals</h3>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: 'var(--ink-soft)', margin: '8px 0 0'}}>I miss offers because they get buried in DMs.</p>
              <div style={{marginTop: '16px', borderTop: '1px solid var(--hairline)', paddingTop: '14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
                <span style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)'}}>Career creator</span>
                <span style={{fontFamily: 'var(--font-ui)', fontSize: '11px', color: 'var(--ink-faint)'}}>@priya.career</span>
              </div>
            </div>
          </div>
        </section>

        <footer style={{background: 'var(--ink)', color: '#EDEDE7', padding: '36px 24px 26px'}}>
          <img src="/guapd-wordmark.svg" alt="guapd" style={{height: '20px', width: 'auto', display: 'block'}} decoding="async" loading="lazy" />
          <p style={{margin: '12px 0 0', fontSize: '13px', lineHeight: '1.6', color: '#9EA096'}}>Match, deal and grow, all in one calm, trusted place.</p>
          <a href="/signup/creator" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', marginTop: '18px', background: 'var(--lime)', color: 'var(--lime-950)', fontWeight: '700', fontSize: '13px', padding: '12px 22px', borderRadius: '999px', textDecoration: 'none'}}>Join as a creator <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M13 6l6 6-6 6" /></svg></a>
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '22px', marginTop: '28px'}}>
            <div>
              <div className="t-meta" style={{fontSize: '10.5px', letterSpacing: '.08em', color: '#6E7066'}}>Product</div>
              <div style={{display: 'flex', flexDirection: 'column', gap: '11px', marginTop: '12px'}}>
                <a href="/creators" style={{fontSize: '12.5px', color: '#9EA096', textDecoration: 'none'}}>For creators</a>
                <a href="/brands" style={{fontSize: '12.5px', color: '#9EA096', textDecoration: 'none'}}>For brands</a>
          
              </div>
            </div>
            <div>
              <div className="t-meta" style={{fontSize: '10.5px', letterSpacing: '.08em', color: '#6E7066'}}>Company</div>
              <div style={{display: 'flex', flexDirection: 'column', gap: '11px', marginTop: '12px'}}>
                <a href="#" style={{fontSize: '12.5px', color: '#9EA096', textDecoration: 'none'}}>About us</a>
                <a href="#" style={{fontSize: '12.5px', color: '#9EA096', textDecoration: 'none'}}>Careers</a>
                <a href="#" style={{fontSize: '12.5px', color: '#9EA096', textDecoration: 'none'}}>Contact</a>
              </div>
            </div>
          </div>
          <div style={{borderTop: '1px solid rgba(255,255,255,.12)', marginTop: '26px', paddingTop: '18px'}}>
            <div style={{fontSize: '11.5px', color: '#7E8076'}}>© 2026 GUAPD Technologies. All rights reserved.</div>
          </div>
        </footer>

      </div>
      </div>
    </div>
  )
}
