'use client'

import { useEffect, useRef, useState } from 'react'
import BookDemoModal from '@/components/BookDemoModal'
import { initLandingEffects } from '@/app/landing-effects'
import { FAQ } from '@/app/LandingPageClient'

/**
 * The landing page, mobile layout — ported from the "GUAPD Landing - Mobile"
 * export.
 *
 * Markup is generated by scripts/landing-mobile-convert-from-export.py — edit
 * the converter and re-run it, not the JSX below.
 *
 * A SEPARATE LAYOUT, not the desktop page reflowed, as on /brands and
 * /creators. Both render and landing-mobile.css picks one at 820px; `display:
 * none` keeps the hidden layout out of the accessibility tree.
 *
 * Every heading is h2 or lower — the desktop layout owns the page's single h1,
 * and both are in the DOM at once.
 */
export default function LandingMobileClient() {
  const rootRef = useRef<HTMLDivElement>(null)
  const [demoOpen, setDemoOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)

  // Same source as the desktop layout, same derived fields the loop reads.
  const faqs = FAQ.map((f, i) => ({
    ...f,
    open: openFaq === i,
    num: String(i + 1).padStart(2, '0'),
    icon: openFaq === i ? 'M5 12h14' : 'M12 5v14M5 12h14',
  }))

  // The same scroll choreography the desktop layout runs — the expanding
  // showcase and the converge panel — pointed at THIS layout's copies via the
  // -m id suffix. Without it the mobile page had no showcase animation and its
  // converge panel stayed at opacity 0, because the effects were driving the
  // hidden desktop elements.
  useEffect(() => {
    const root = rootRef.current
    if (!root) return
    const stop = initLandingEffects(root, '-m')

    // The closing section has its OWN choreography on mobile, and the desktop
    // driver in landing-effects cannot run it: that one needs #cvPin and a pair
    // of converging bars, neither of which exists in this export. It bails on
    // the missing pin — which is why the neon circle stayed at scale(0) and the
    // four content elements sat at opacity 0, so the section read as missing.
    //
    // Transcribed from _initConverge in the export's own script, values intact:
    // the circle blows up to 30x with a quarter turn while the words fade up.
    const sec = root.querySelector<HTMLElement>('#cvSec-m')
    const circle = root.querySelector<HTMLElement>('#cvCircle-m')
    const content = ['cvEyebrow-m', 'cvHead-m', 'cvSub-m', 'cvBtn-m']
      .map((id) => root.querySelector<HTMLElement>('#' + id))

    const play = () => {
      if (circle) {
        circle.style.transition = 'transform 1.1s cubic-bezier(.16,1,.3,1)'
        requestAnimationFrame(() => {
          circle.style.transform = 'translate(-50%,-50%) scale(30) rotate(90deg)'
        })
      }
      content.forEach((el) => {
        if (el) { el.style.opacity = '1'; el.style.transform = 'translateY(0)' }
      })
    }

    // Reduced motion still has to SHOW the section: the elements start hidden
    // in the markup, so doing nothing would leave it permanently blank.
    if (typeof IntersectionObserver === 'undefined' ||
        window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      content.forEach((el) => {
        if (el) { el.style.opacity = '1'; el.style.transform = 'translateY(0)' }
      })
      if (circle) circle.style.transform = 'translate(-50%,-50%) scale(30)'
      return stop
    }

    let cvObserver: IntersectionObserver | undefined
    if (sec && circle) {
      cvObserver = new IntersectionObserver(
        (entries) => entries.forEach((e) => {
          if (e.isIntersecting) { play(); cvObserver?.disconnect() }
        }),
        { threshold: 0.4 },
      )
      cvObserver.observe(sec)
    }

    return () => { cvObserver?.disconnect(); stop() }
  }, [])

  useEffect(() => {
    const bar = document.getElementById('landProgress')
    const onScroll = () => {
      if (!bar) return
      const d = document.documentElement
      const p = d.scrollTop / ((d.scrollHeight - d.clientHeight) || 1)
      bar.style.width = `${Math.min(100, Math.max(0, p * 100))}%`
    }
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    window.addEventListener('resize', onScroll)
    const stopScroll = () => {
      window.removeEventListener('scroll', onScroll)
      window.removeEventListener('resize', onScroll)
    }

    const nodes = Array.from(document.querySelectorAll('.landing-mobile .sr'))
    if (!nodes.length) return stopScroll
    if (typeof IntersectionObserver === 'undefined') {
      nodes.forEach((n) => n.classList.add('sr-in'))
      return stopScroll
    }
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            e.target.classList.add('sr-in')
            io.unobserve(e.target)
          }
        })
      },
      { rootMargin: '0px 0px -12% 0px', threshold: 0.05 },
    )
    nodes.forEach((n) => io.observe(n))
    return () => { io.disconnect(); stopScroll() }
  }, [])

  return (
    <div className="landing-mobile" ref={rootRef}>
      <div id="landProgress" style={{position: 'fixed', top: '0', left: '0', height: '2px', width: '0%', background: 'var(--neon-deep)', zIndex: '200', transition: 'width .1s linear'}}></div>

      <div className="mobile-frame">
      <div style={{fontFamily: 'var(--font-ui)', color: 'var(--ink)', position: 'relative', overflowX: 'clip', background: '#fff'}}>

        {/* NAV */}
        <div style={{position: 'sticky', top: '0', zIndex: '100'}}>
    
        </div>

        {/* HERO */}
        <section className="sr hr" style={{padding: '56px 24px 32px', textAlign: 'center'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}><span style={{width: '5px', height: '5px', borderRadius: '50%', background: 'var(--ink)', flexShrink: '0'}}></span>Brands &amp; creators</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '30px', lineHeight: '1.35', margin: '24px 0 0', color: 'var(--ink)'}}>Where collaborations <span className="opit">get guapd.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '24px auto 0', maxWidth: '30ch'}}>No more DMs, spreadsheets or awkward payment follow-ups. Just deals that move.</p>
        </section>
        <div style={{padding: '0 24px', marginTop: '24px', marginBottom: '56px'}}><img src="/landing-mobile/93c762d7.webp" alt="guapd total earnings, my deals, and upcoming payment" style={{width: '100%', aspectRatio: '1060/1484', objectFit: 'contain', display: 'block', borderRadius: '28px'}} decoding="async" loading="lazy" /></div>

        {/* ONE CONNECTED SYSTEM */}
        <section className="sr hr" style={{padding: '88px 0 96px', background: 'var(--ink)'}}>
          <div style={{padding: '0 32px'}}>
            <span className="opill" style={{fontSize: '9px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '5px 13px'}}><span style={{width: '5px', height: '5px', borderRadius: '50%', background: 'var(--ink)', flexShrink: '0'}}></span>One connected system</span>
            <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '24px', margin: '22px 0 0', color: '#fff', whiteSpace: 'nowrap'}}>Everything, <span className="opit" style={{color: 'var(--neon)'}}>in one place.</span></h2>
            <p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#9EA096', margin: '12px 0 0'}}>One system for offers, terms, delivery and payment.</p>
          </div>
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginTop: '40px', padding: '0 24px'}}>
            <div className="sr" style={{border: '1px solid rgba(255,255,255,.14)', borderRadius: '16px', padding: '20px 16px', '--sr-delay': '0s'}}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 3 14h9l-1 8 10-12h-9z" /></svg>
              <div style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '14.5px', color: '#fff', marginTop: '14px', lineHeight: '1.3'}}>One thread, offer to payout</div>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', lineHeight: '1.5', color: '#9EA096', margin: '6px 0 0'}}>Same four steps, every deal.</p>
            </div>
            <div className="sr" style={{border: '1px solid rgba(255,255,255,.14)', borderRadius: '16px', padding: '20px 16px', '--sr-delay': '.08s'}}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 3" /></svg>
              <div style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '14.5px', color: '#fff', marginTop: '14px', lineHeight: '1.3'}}>Always know where things stand</div>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', lineHeight: '1.5', color: '#9EA096', margin: '6px 0 0'}}>Every state change is recorded.</p>
            </div>
            <div className="sr" style={{border: '1px solid rgba(255,255,255,.14)', borderRadius: '16px', padding: '20px 16px', '--sr-delay': '.16s'}}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>
              <div style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '14.5px', color: '#fff', marginTop: '14px', lineHeight: '1.3'}}>No more scattered DMs</div>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', lineHeight: '1.5', color: '#9EA096', margin: '6px 0 0'}}>Terms and payment, solved by design.</p>
            </div>
            <div className="sr" style={{border: '1px solid rgba(255,255,255,.14)', borderRadius: '16px', padding: '20px 16px', '--sr-delay': '.24s'}}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" /><path d="M3 10h18" /></svg>
              <div style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '14.5px', color: '#fff', marginTop: '14px', lineHeight: '1.3'}}>Every deal, one queue</div>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', lineHeight: '1.5', color: '#9EA096', margin: '6px 0 0'}}>Ranked by what needs attention.</p>
            </div>
          </div>
        </section>

        {/* YOUR DASHBOARD */}
        <section className="sr hr" style={{padding: '56px 24px', textAlign: 'center'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Your deals, your dashboard</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '23px', margin: '6px 0 0', color: 'var(--ink)'}}>Everything, always in <span className="opit">view.</span></h2>
          <div style={{borderRadius: '16px', overflow: 'hidden', marginTop: '32px'}}>
            <img src="/landing-mobile/dc7c1444.webp" alt="guapd my deals with active offer, deliverables, and quick actions" style={{width: '100%', height: 'auto', display: 'block', marginTop: '-16px'}} width={643} height={900} decoding="async" loading="lazy" />
          </div>
          <a href="#" className="cta" style={{width: '100%', marginTop: '28px', background: 'var(--ink)', color: '#fff'}}>Get early access</a>
        </section>

        {/* HERO */}
        <section className="sr sr" id="top-m" style={{position: 'relative'}}>
          <div style={{position: 'relative', aspectRatio: '4/5', overflow: 'hidden'}}>
            <img src="/landing-mobile/8fd5a2c6.webp" alt="guapd campaign brief, creator, invoice and deliverable glass panel" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 55%', display: 'block'}} width={900} height={672} decoding="async" loading="lazy" />
            <div style={{position: 'absolute', inset: '0', background: 'linear-gradient(180deg,#fff 0%,rgba(255,255,255,.95) 30%,rgba(255,255,255,.55) 55%,rgba(255,255,255,0) 75%)'}}></div>
            <div style={{position: 'absolute', left: '0', right: '0', top: '0', padding: '24px 24px 0', textAlign: 'center'}}>
              <span className="opill" style={{fontSize: '9px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 14px', display: 'inline-flex'}}>Brand deals, reinvented</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.15', fontSize: '22px', margin: '14px auto 0', color: 'var(--ink)', maxWidth: '24ch'}}>Creator deals, <span className="opit">without the chaos.</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.5', color: 'var(--ink-soft)', margin: '10px auto 0', maxWidth: '26ch'}}>One calm place for offers, terms, delivery and payment.</p>
            </div>
          </div>
        </section>

        {/* FOR BRANDS / FOR CREATORS */}
        <section className="sr sr" style={{position: 'relative'}}>
          <div className="sr" style={{background: 'var(--ink)', padding: '56px 24px 96px', color: '#fff', display: 'flex', flexDirection: 'column', clipPath: 'polygon(0 0,100% 0,100% 74%,0 100%)'}}>
            <img src="/landing-mobile/4869d577.webp" alt="guapd campaign overview with budget utilization and deliverables status" style={{width: '100%', height: 'auto', display: 'block', borderRadius: '14px'}} width={900} height={720} decoding="async" loading="lazy" />
            <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px', width: 'fit-content', marginTop: '28px'}}>For brands</span>
            <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '24px', lineHeight: '1.2', margin: '14px 0 0'}}>Every campaign, <span className="opit" style={{color: 'var(--neon)'}}>on track.</span></h3>
            <p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#8E9086', margin: '12px 0 0', maxWidth: '26ch'}}>Discover creators, manage campaigns, approve deliverables and track spend.</p>
            <a href="/brands" style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '12.5px', color: '#F3F4EE', borderBottom: '1px solid rgba(243,244,238,.35)', paddingBottom: '3px', width: 'fit-content', marginTop: '16px'}}>Explore for brands →</a>
          </div>
          <div className="sr" style={{padding: '40px 24px 32px', display: 'flex', flexDirection: 'column', marginTop: '-40px', alignItems: 'flex-end', textAlign: 'right', '--sr-delay': '.1s'}}>
            <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px', width: 'fit-content'}}>For creators</span>
            <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '24px', lineHeight: '1.2', color: 'var(--ink)', margin: '14px 0 0'}}>Your whole hustle, <span className="opit">organized.</span></h3>
            <p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#565C68', margin: '12px 0 0', maxWidth: '26ch'}}>Accept, counter, deliver, and get paid, without a single DM.</p>
            <a href="/creators" style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '12.5px', color: 'var(--ink)', borderBottom: '1px solid rgba(18,21,28,.25)', paddingBottom: '3px', width: 'fit-content', marginTop: '16px'}}>Explore for creators →</a>
                  <img src="/landing-mobile/0553911e.webp" alt="guapd total earnings, my deals, and upcoming payment" style={{width: '100%', height: 'auto', display: 'block', borderRadius: '14px', marginTop: '28px'}} width={643} height={900} decoding="async" loading="lazy" />
          </div>
        </section>

        {/* INSIDE A DEAL */}
        <section className="sr hr" style={{padding: '56px 24px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Inside guapd</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '24px', margin: '20px 0 0', color: 'var(--ink)'}}>Built for how deals <span className="opit">actually happen.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.6', color: 'var(--ink-soft)', margin: '14px 0 0', maxWidth: '32ch'}}>Every offer, term and delivery lives in one shared record. Brands and creators always see the same thing.</p>
          <div style={{display: 'flex', flexDirection: 'column', gap: '14px', marginTop: '32px'}}>
            <div className="mos-cell" data-mos="" style={{borderRadius: '16px', aspectRatio: '1672/941'}}><img src="/landing-mobile/7c14e70c.webp" alt="Two glass panels showing brand-side campaign command center and creator-side dashboard" style={{objectFit: 'contain'}} width={900} height={507} decoding="async" loading="lazy" /></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px'}}>
              <div className="mos-cell" data-mos="" style={{borderRadius: '16px', aspectRatio: '1/1', transitionDelay: '.08s'}}><img src="/landing-mobile/dc7ee0fa.webp" alt="Phone showing creator dashboard with new opportunities, active deal, and payment received" style={{objectPosition: 'center 45%'}} width={900} height={720} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos="" style={{borderRadius: '16px', aspectRatio: '1/1', transitionDelay: '.16s'}}><img src="/landing-mobile/2507fc5c.webp" alt="Glass panel showing deliverables list" width={643} height={900} decoding="async" loading="lazy" /></div>
            </div>
          </div>
        </section>

        {/* HOW IT WORKS */}
        <section id="how-m" className="sr hr" style={{background: 'var(--ink)', padding: '56px 24px', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}>How it works</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '27px', margin: '18px 0 0', color: '#fff'}}>Four steps, <span className="opit" style={{color: 'var(--neon)'}}>start to finish.</span></h2>
          <div style={{marginTop: '32px', position: 'relative'}}>
            <div style={{position: 'absolute', left: '9px', top: '10px', bottom: '10px', width: '1px', background: 'rgba(255,255,255,.18)'}}></div>
            <div className="sr" style={{display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '14px', position: 'relative'}}><span style={{width: '19px', height: '19px', borderRadius: '50%', background: '#181C24', border: '1px solid rgba(255,255,255,.3)', flexShrink: '0', position: 'relative', zIndex: '1'}}></span><div style={{flex: '1', padding: '16px', border: '1px solid rgba(255,255,255,.16)', borderRadius: '14px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '15px', color: '#fff'}}>Send a structured brief</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: '#9EA096', margin: '6px 0 0'}}>Deliverables, rate, timeline and payment split, agreed before work starts.</p></div></div>
            <div className="sr" style={{display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '14px', position: 'relative'}}><span style={{width: '19px', height: '19px', borderRadius: '50%', background: '#181C24', border: '1px solid rgba(255,255,255,.3)', flexShrink: '0', position: 'relative', zIndex: '1'}}></span><div style={{flex: '1', padding: '16px', border: '1px solid rgba(255,255,255,.16)', borderRadius: '14px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '15px', color: '#fff'}}>Lock the terms in writing</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: '#9EA096', margin: '6px 0 0'}}>Every offer and counter is timestamped. The final number becomes the contract.</p></div></div>
            <div className="sr" style={{display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '14px', position: 'relative'}}><span style={{width: '19px', height: '19px', borderRadius: '50%', background: '#181C24', border: '1px solid rgba(255,255,255,.3)', flexShrink: '0', position: 'relative', zIndex: '1'}}></span><div style={{flex: '1', padding: '16px', border: '1px solid rgba(255,255,255,.16)', borderRadius: '14px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '15px', color: '#fff'}}>Upload, review, approve</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: '#9EA096', margin: '6px 0 0'}}>Revisions are counted against what was agreed, so scope stays put.</p></div></div>
            <div className="sr" style={{display: 'flex', alignItems: 'center', gap: '14px', position: 'relative'}}><span style={{width: '19px', height: '19px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0', position: 'relative', zIndex: '1'}}></span><div style={{flex: '1', padding: '16px', border: '1px solid rgba(255,255,255,.16)', borderRadius: '14px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '15px', color: '#fff'}}>Watch the money move</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', lineHeight: '1.55', color: '#9EA096', margin: '6px 0 0'}}>Live status from agreed to paid, visible to both sides.</p></div></div>
          </div>
        </section>

        {/* SCROLL EXPAND MASCOT */}
        <section className="sr sr" id="expandSection-m" style={{position: 'relative', height: '130vh'}}>
          <div id="expandPin-m" style={{position: 'absolute', top: '0', left: '0', width: '100%', height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden'}}>
            <img id="bgImg-m" src="/landing-mobile/942fb4b1.webp" alt="" style={{position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', width: 'auto', height: 'auto', maxWidth: 'none', objectFit: 'none', willChange: 'opacity'}} width={900} height={507} decoding="async" loading="lazy" />
            <img id="expandImg-m" src="/landing-mobile/01531bb2.webp" alt="guapd" style={{position: 'relative', zIndex: '1', borderRadius: '24px', boxShadow: '0 30px 70px -20px rgba(20,22,10,.35)', objectFit: 'cover', willChange: 'width,height'}} width={900} height={900} decoding="async" loading="lazy" />
          </div>
        </section>

        {/* DEALS ON GUAPD */}
  

        {/* FEATURED CAMPAIGNS */}
  

        {/* CREATORS ON GUAPD */}
  

        {/* BRANDS WE WORK WITH */}
  

        {/* FAQ */}
        <section className="sr hr" style={{padding: '56px 24px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>FAQ</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '22px', margin: '20px 0 0', color: 'var(--ink)'}}>Questions, <span className="opit">answered.</span></h2>
          <div style={{marginTop: '16px'}}>
            {faqs.map((f, i) => (
              <div key={i} onClick={() => setOpenFaq(openFaq === i ? -1 : i)} className="hr" style={{display: 'grid', gridTemplateColumns: '34px 1fr 16px', padding: '20px 0', cursor: 'pointer'}}>
                <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: '19px', color: 'var(--ink-faint)', lineHeight: '1'}}>{f.num}</span>
                <div>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '15px'}}>{f.q}</span>
                  {f.open && (<>
                    <p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '12px 0 0'}}>{f.a}</p>
                  </>)}
                </div>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--ink-faint)" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0', marginTop: '3px'}}><path d={f.icon} /></svg>
              </div>
            ))}
          </div>
        </section>

        {/* CONVERGE, two sides meet */}
        <section className="sr sr" id="cvSec-m" style={{position: 'relative', width: '100%', minHeight: '70vh', padding: '64px 24px', overflow: 'hidden', background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
          <div id="cvCircle-m" style={{position: 'absolute', left: '50%', top: '50%', width: '90px', height: '90px', borderRadius: '50%', background: 'var(--neon)', marginLeft: '-45px', marginTop: '-45px', transform: 'scale(0)', transition: 'transform .7s cubic-bezier(.16,1,.3,1)'}}></div>
          <div style={{position: 'relative', zIndex: '2', maxWidth: '300px', textAlign: 'center'}}>
            <div id="cvEyebrow-m" style={{color: 'var(--ink)', fontFamily: 'var(--font-ui)', fontSize: '10px', fontWeight: '600', letterSpacing: '.12em', textTransform: 'uppercase', opacity: '0', transition: 'opacity .5s ease .15s,transform .5s ease .15s', transform: 'translateY(12px)'}}>Two sides</div>
            <h2 id="cvHead-m" style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.15', fontSize: '26px', margin: '14px 0 0', color: 'var(--ink)', opacity: '0', transition: 'opacity .5s ease .22s,transform .5s ease .22s', transform: 'translateY(12px)'}}>Where collaborations <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>get guapd.</span></h2>
            <p id="cvSub-m" style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: 'var(--ink)', maxWidth: '280px', margin: '14px auto 0', opacity: '0', transition: 'opacity .5s ease .29s,transform .5s ease .29s', transform: 'translateY(12px)'}}>One flow for briefs, terms and payouts, built for both sides of the deal.</p>
            <div id="cvBtn-m" style={{marginTop: '22px', display: 'inline-flex', opacity: '0', transition: 'opacity .5s ease .36s,transform .5s ease .36s', transform: 'translateY(12px)'}}>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'var(--ink)', border: 'none', color: '#fff', borderRadius: '999px', padding: '12px 22px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '13px'}}>Book demo</span>
            </div>
          </div>
        </section>

  

      </div>
      </div>
      <BookDemoModal open={demoOpen} onClose={() => setDemoOpen(false)} />
    </div>
  )
}
