'use client'

import { useEffect, useState } from 'react'
import { initLandingEffects } from '@/app/landing-effects'

/**
 * The landing page, ported from the "Landing - desktop" design export.
 *
 * Markup is generated by scripts/landing-convert-from-export.py — edit the
 * converter and re-run it rather than editing the JSX below, or the next port
 * silently drops the change.
 *
 * A client component because the design is scroll-driven throughout: pinned
 * sequences, a scrubbed card stack, count-ups and reveals, all of which need
 * the real scroll position. The choreography itself lives in landing-effects.ts,
 * transcribed from the export so the timings stay exactly as designed.
 *
 * The two data sets are the export's own. They are placeholder content — the
 * campaigns in particular name brands that are not ours — and are here so the
 * full page can be reviewed before deciding what to keep, hide or replace with
 * real data.
 */

const CAMPAIGNS = [
      { id:'lc1', num:'01', category:'Nextlevel Studio', name:'Summer Reel campaign', deliverables: 3, top: 96 },
      { id:'lc2', num:'02', category:'Aura Brand Identity', name:'Launch teaser', deliverables: 2, top: 124 },
      { id:'lc3', num:'03', category:'Solaris Digital', name:'Product spotlight', deliverables: 4, top: 152 }
    ]

const FAQ = [
      { q: 'How do usage rights work?', a: 'Usage rights are agreed as part of the offer \u2014 organic only, organic plus paid boosting, or full commercial \u2014 with an optional expiry date (blank means perpetual). Paid boosting is set per deliverable. Whatever you agree is recorded on the deal.' },
      { q: 'What about revisions?', a: 'Each deal specifies how many revisions are included and the cost of any extra. As revisions are requested, the used-vs-included count is tracked automatically, so both sides always know where they stand.' },
      { q: 'When does the creator get paid?', a: 'Payment terms are set in the offer \u2014 100% advance, 100% on approval, or 50-50. The creator always receives their full rate; GUAPD\u2019s 15% fee is added on top and paid by the brand.' },
      { q: 'How do product shipments work?', a: 'If a deal involves shipping a product, the brand marks it as a shipment deal and adds shipping details. The deal then tracks a \u201cproduct delivered\u201d step alongside the content deliverables.' },
      { q: 'What happens in a dispute?', a: 'Because every offer, counter, agreed term, submission and payment is timestamped and on record, there\u2019s a single source of truth \u2014 no WhatsApp screenshots. That record is what any dispute is resolved against.' },
      { q: 'What if a creator has no shopfront?', a: 'A shopfront isn\u2019t required. Brands can send an offer to any creator profile; the creator receives it, and can accept, counter or decline just the same. A shopfront simply makes packages easier to browse.' }
    ]

export default function LandingPageClient() {
  const [openFaq, setOpenFaq] = useState(0)

  useEffect(() => initLandingEffects(), [])

  // The export's own view model: the loop reads f.num/f.icon/f.open, so the
  // derived fields are built here rather than inlined into the markup.
  const campaigns = CAMPAIGNS
  const faqs = FAQ.map((f, i) => ({
    ...f,
    open: openFaq === i,
    num: String(i + 1).padStart(2, '0'),
    icon: openFaq === i ? 'M5 12h14' : 'M12 5v14M5 12h14',
  }))

  return (
    <div className="landing-page">
      <div style={{fontFamily: 'var(--font-ui)', color: 'var(--ink)', position: 'relative', overflowX: 'hidden', background: '#fff'}}>

        <div id="scrollProgress" style={{position: 'fixed', top: '0', left: '0', height: '2px', width: '0%', background: 'var(--ink)', zIndex: '200'}}></div>

        {/* NAV */}
        <div style={{position: 'sticky', top: '0', zIndex: '100', padding: '26px clamp(14px,4vw,28px) 0'}}>
    
        </div>

        {/* ============ CAMPAIGN DASHBOARD SHOWCASE (from For Brands) ============ */}
        <section style={{position: 'relative', width: '100vw', left: '50%', right: '50%', marginLeft: '-50vw', marginRight: '-50vw', marginTop: 'clamp(-96px,-8vw,-70px)', overflow: 'hidden', background: '#fff', zIndex: '0', paddingBottom: '40px'}}>
          <div style={{position: 'relative', overflow: 'hidden', width: '92%', margin: '0 auto'}}>
            <img src="/landing/gemini-generated-image-waw95uwaw95uwaw9.webp" alt="guapd campaign brief, creator, invoice and deliverable glass panel" style={{position: 'relative', top: '-145px', left: '0', width: '100%', height: 'auto', display: 'block', marginBottom: '-145px'}} decoding="async" />
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', left: '0', width: '8%', background: 'linear-gradient(to right,#fff 0%,rgba(255,255,255,0) 100%)', pointerEvents: 'none', zIndex: '1'}}></div>
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', right: '0', width: '8%', background: 'linear-gradient(to left,#fff 0%,rgba(255,255,255,0) 100%)', pointerEvents: 'none', zIndex: '1'}}></div>
          </div>
          <div style={{position: 'absolute', zIndex: '2', left: '14%', top: 'calc(8% + 105px)', width: 'min(46%,520px)', minWidth: '200px', textAlign: 'left'}}>
            <div aria-hidden="true" style={{position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', width: '680px', height: '680px', borderRadius: '50%', background: 'radial-gradient(circle,rgba(255,255,255,0.85) 0%,rgba(255,255,255,0) 70%)', zIndex: '-1', pointerEvents: 'none'}}></div>
            <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.03em', lineHeight: '1.02', fontSize: 'clamp(44px,3.2vw,56px)', margin: '0', color: '#12151C'}}>The operating system for <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>creator deals.</span></h2>
            <p style={{fontFamily: 'var(--font-ui)', fontSize: '16px', lineHeight: '1.55', color: '#565C68', margin: '22px 0 0', maxWidth: '44ch'}}>Brands and creators, in one shared space, offers, approvals, deliverables and payments, start to finish.</p>
            <button type="button" style={{marginTop: '28px', background: '#12151C', color: '#fff', border: 'none', borderRadius: '999px', padding: '12px 24px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '700', cursor: 'pointer'}}>Book demo</button>
          </div>
        </section>

        {/* HERO — animated headline + mascot + product visual */}
        <section id="top" style={{position: 'relative', overflow: 'visible', background: '#fff', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px) clamp(56px,6vw,88px)'}}>
          <div className="gx" style={{position: 'relative', textAlign: 'center', maxWidth: '760px'}}>
            <span className="hero-in" style={{'--hd': '0s', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '10.5px', letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Brand deals, reinvented</span>
            <h1 className="hero-in" style={{'--hd': '.08s', fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.03em', lineHeight: '1.0', fontSize: 'clamp(34px,4.6vw,52px)', margin: '18px auto 0', maxWidth: '17ch', color: 'var(--ink)'}}>Creator deals without the <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>chaos.</span></h1>
            <p className="hero-in" style={{'--hd': '.16s', fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '34ch', margin: '18px auto 0'}}>One calm place to send offers, agree terms, deliver content, and track payment.</p>
            <div className="hero-in" style={{'--hd': '.24s', display: 'flex', justifyContent: 'center', marginTop: '26px'}}><div className="magnet"><a href="/signup/brand" className="lp-btn">Book demo</a></div></div>
          </div>
        </section>
  

        {/* ============ GLASS PANEL SHOWCASE (Built for brands) ============ */}
        <section className="sr" style={{position: 'relative', background: '#fff', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)', overflow: 'hidden'}}>
          <div style={{position: 'relative', maxWidth: '1200px', margin: '0 auto', borderRadius: '32px', overflow: 'hidden', boxShadow: '0 20px 40px -30px rgba(40,45,25,.18)'}}>
            <img src="/landing/chatgpt-image-aug-18-2026-05-22-57-pm.webp" alt="Glass panels showing brand-side creator discovery, campaign management, approvals, and reporting" style={{width: '80%', height: 'auto', display: 'block', marginLeft: 'auto', filter: 'saturate(0.9) contrast(1.08) brightness(1.02)'}} decoding="async" loading="lazy" />
            <div aria-hidden="true" style={{position: 'absolute', top: '0', right: '0', width: '80%', height: '100%', background: 'linear-gradient(200deg,rgba(80,140,230,0.14),rgba(80,140,230,0.03) 60%)', mixBlendMode: 'multiply', pointerEvents: 'none'}}></div>
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', left: '0', width: '34%', background: 'linear-gradient(to right,#fff 0%,#fff 55%,rgba(255,255,255,0) 100%)', pointerEvents: 'none'}}></div>
            <div style={{position: 'absolute', top: '50%', left: '9%', transform: 'translateY(-50%)', width: 'min(30%,360px)', minWidth: '220px', textAlign: 'left'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Built for you</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(30px,3.1vw,44px)', margin: '12px 0 0', color: '#12151C'}}>Every campaign, <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>on track.</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: '#565C68', margin: '16px 0 0', maxWidth: '30ch'}}>Discover creators, manage campaigns, approve deliverables and track reporting — all tracked in one dashboard.</p>
            </div>
          </div>
        </section>

        {/* MOSAIC IMAGE GRID */}
  


        {/* HOW IT WORKS — pinned, scroll-driven */}
        <section id="how" className="hw-sec">
          <div className="hw-pin">
            <div className="hw-tints">
              <div className="hw-tint" data-hw-tint="0" style={{background: '#E9F7F0'}}></div>
              <div className="hw-tint" data-hw-tint="1" style={{background: '#E7F1FC'}}></div>
              <div className="hw-tint" data-hw-tint="2" style={{background: '#F0EAFD'}}></div>
              <div className="hw-tint" data-hw-tint="3" style={{background: '#FCF6E4'}}></div>
            </div>
            <div className="hw-topbar" id="hwTopbar" style={{flexDirection: 'column', alignItems: 'flex-start', gap: '2px', transition: 'opacity .5s ease'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(28px,3.8vw,48px)', letterSpacing: '-.02em', lineHeight: '1.05', margin: '0'}}>How it <span className="t-accent">works</span></h2>
            </div>
            <div className="hw-clip">
            <div className="hw-inner">
              <div className="hw-grid">
                <div className="hw-stage">
            <div className="hw-card" data-hw-card="0" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>New brief</span><span>Draft</span></div>
              <div style={{display: 'flex', alignItems: 'center', gap: '18px', marginTop: 'clamp(18px,2.4vw,30px)'}}>
                <div style={{width: '64px', height: '64px', borderRadius: '50%', background: '#F2EEFC', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '19px', color: 'var(--sec-ink)', flexShrink: '0'}}>AR</div>
                <div><div style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '24px', letterSpacing: '-.02em'}}>Ananya Rao</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)', marginTop: '3px'}}>@ananyarao · 180K followers</div></div>
              </div>
              <div style={{marginTop: 'clamp(16px,2.2vw,28px)', borderTop: '1px solid var(--hairline)'}}>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: '1px solid var(--hairline)', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>deliverables</span><span style={{fontWeight: '600'}}>1 Reel + 2 Stories</span></div>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: '1px solid var(--hairline)', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>rate</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '21px'}}>₹45,000</span></div>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: '1px solid var(--hairline)', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>live by</span><span style={{fontWeight: '600'}}>24 Aug</span></div>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: 'none', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>payment</span><span style={{fontWeight: '600'}}>50% upfront · 50% on approval</span></div>
              </div>
              <div style={{flex: '1', minHeight: '12px'}}></div>
              <div style={{background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '17px', textAlign: 'center', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '17px'}}>Send offer</div>
            </div>
            <div className="hw-card" data-hw-card="1" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>Negotiation</span><span>3 messages</span></div>
              <div style={{flex: '1', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '16px', padding: 'clamp(16px,2.4vw,30px) 0'}}>
                <div style={{alignSelf: 'flex-end', maxWidth: '78%', background: '#EAF1FB', borderRadius: '20px 20px 6px 20px', padding: '15px 19px', fontFamily: 'var(--font-ui)', fontSize: '16px'}}>Offer · ₹45,000 for 1 Reel + 2 Stories<div style={{fontSize: '13px', color: 'var(--ink-soft)', marginTop: '5px'}}>brand · 10:04</div></div>
                <div style={{alignSelf: 'flex-start', maxWidth: '78%', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '20px 20px 20px 6px', padding: '15px 19px', fontFamily: 'var(--font-ui)', fontSize: '16px'}}>Counter · ₹50,000, usage rights 60 days<div style={{fontSize: '13px', color: 'var(--ink-soft)', marginTop: '5px'}}>creator · 10:26</div></div>
                <div style={{alignSelf: 'flex-end', maxWidth: '78%', background: '#EAF1FB', borderRadius: '20px 20px 6px 20px', padding: '15px 19px', fontFamily: 'var(--font-ui)', fontSize: '16px'}}>₹48,000 final, 45 days usage<div style={{fontSize: '13px', color: 'var(--ink-soft)', marginTop: '5px'}}>brand · 11:02</div></div>
              </div>
              <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '14px', background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '16px 24px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '17px'}}><span>Terms locked</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '800'}}>₹48,000</span></div>
            </div>
            <div className="hw-card" data-hw-card="2" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>Deliverable</span><span>in review</span></div>
              <div style={{flex: '1', margin: 'clamp(16px,2.4vw,28px) 0', border: '1.5px dashed rgba(24,28,36,.2)', borderRadius: '24px', background: '#FBFCFD', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '10px'}}>
                <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="var(--ink)" strokeWidth="1.7"><path d="M12 16V4" /><path d="m6 10 6-6 6 6" /><path d="M4 20h16" /></svg>
                <div style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '22px', letterSpacing: '-.02em'}}>Reel_v2.mp4</div>
                <div style={{fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)'}}>uploaded 18 Aug · 42 MB</div>
              </div>
              <div style={{display: 'flex', justifyContent: 'space-between', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>revisions</span><span style={{fontWeight: '600'}}>1 of 2 used</span></div>
              <div style={{display: 'flex', gap: '6px', marginTop: '12px'}}><div style={{flex: '1', height: '9px', borderRadius: '5px', background: 'var(--neon-deep)'}}></div><div style={{flex: '1', height: '9px', borderRadius: '5px', background: 'rgba(18,21,28,.12)'}}></div></div>
              <div style={{marginTop: '18px', fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)'}}>Approval due in 2 days, or it clears automatically.</div>
            </div>
            <div className="hw-card" data-hw-card="3" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>Payment</span><span>escrow</span></div>
              <div style={{flex: '1', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '20px', padding: 'clamp(16px,2.4vw,26px) 0', fontFamily: 'var(--font-ui)', fontSize: '17px'}}>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0'}}></span>Terms agreed · ₹48,000</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0'}}></span>Content approved</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0'}}></span>Payout released</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px', color: 'var(--ink-soft)'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: '#fff', border: '1.5px solid var(--hairline)', flexShrink: '0'}}></span>In your account · 14 Aug</div>
              </div>
              <div style={{borderTop: '1px solid var(--hairline)', paddingTop: '20px', display: 'flex', alignItems: 'baseline', justifyContent: 'space-between'}}>
                <span style={{fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)'}}>paid out</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(34px,4vw,50px)', letterSpacing: '-.03em'}}>₹48,000</span>
              </div>
            </div>
                </div>
                <div className="hw-copy">
            <div className="hw-text" data-hw-text="0">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>01</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Offer</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Send a structured brief</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Deliverables, rate, timeline and payment split — written down and agreed before any work starts.</p>
            </div>
            <div className="hw-text" data-hw-text="1">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>02</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Agree</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Lock the terms in writing</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Every offer and counter is timestamped. The final number becomes the contract both sides sign.</p>
            </div>
            <div className="hw-text" data-hw-text="2">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>03</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Deliver</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Upload, review, approve</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Revisions are counted against what was agreed, so scope stays where you left it.</p>
            </div>
            <div className="hw-text" data-hw-text="3">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>04</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Get paid</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Watch the money move</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Live status from agreed to paid, visible to both sides. Nobody has to chase anyone.</p>
            </div>
                </div>
              </div>
            </div>
            </div>
            <div className="hw-dots"><span className="hw-dot" data-hw-dot="0"></span><span className="hw-dot" data-hw-dot="1"></span><span className="hw-dot" data-hw-dot="2"></span><span className="hw-dot" data-hw-dot="3"></span></div>
            </div>
    
          <div className="hw-stack">
            <div className="sr" style={{maxWidth: '660px', margin: '0 auto clamp(20px,4vw,32px)'}}>
              <h2 className="t-title" style={{fontSize: 'clamp(28px,3.8vw,48px)', margin: '0'}}>How it works</h2>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: 'none'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '9px'}}><div style={{display: 'flex', justifyContent: 'space-between', fontSize: '11.5px', color: 'var(--ink-soft)'}}><span>New brief</span><span>Draft</span></div><div style={{display: 'flex', alignItems: 'center', gap: '11px'}}><div style={{width: '36px', height: '36px', borderRadius: '50%', background: '#F7F4FB', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '12px', color: 'var(--sec-ink)'}}>AR</div><div><div style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '13px'}}>Ananya Rao</div><div style={{fontSize: '10.5px', color: 'var(--ink-soft)'}}>@ananyarao · 180K</div></div></div><div style={{display: 'flex', justifyContent: 'space-between', paddingTop: '9px', borderTop: '1px solid var(--hairline)', fontSize: '12px'}}><span style={{color: 'var(--ink-soft)'}}>deliverable</span><span style={{fontWeight: '600'}}>1 Reel</span></div><div style={{display: 'flex', justifyContent: 'space-between', fontSize: '12px'}}><span style={{color: 'var(--ink-soft)'}}>rate</span><span style={{fontWeight: '700'}}>₹45,000</span></div><div style={{marginTop: '6px', background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '8px', textAlign: 'center', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '12px'}}>Send offer</div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>01</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Offer</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Send a structured brief</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Deliverables, rate, timeline, and payment split — written down before any work starts.</p>
              </div>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: '1px solid var(--hairline)'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '7px'}}><div style={{fontSize: '11.5px', color: 'var(--ink-soft)'}}>Negotiation</div><div style={{alignSelf: 'flex-end', background: '#F4F8FC', borderRadius: '12px 12px 3px 12px', padding: '7px 11px', fontSize: '11.5px'}}>Offer · ₹45,000</div><div style={{alignSelf: 'flex-start', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '12px 12px 12px 3px', padding: '7px 11px', fontSize: '11.5px'}}>Counter · ₹50,000</div><div style={{alignSelf: 'flex-end', background: '#F4F8FC', borderRadius: '12px 12px 3px 12px', padding: '7px 11px', fontSize: '11.5px'}}>₹48,000 final</div><div style={{alignSelf: 'center', marginTop: '5px', background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '7px 13px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '11px'}}>Locked · ₹48,000</div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>02</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Agree</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Lock terms, in writing</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Every offer and counter is timestamped. The final number becomes the contract.</p>
              </div>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: '1px solid var(--hairline)'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '9px'}}><div style={{fontSize: '11.5px', color: 'var(--ink-soft)'}}>Deliverable</div><div style={{border: '1.5px dashed rgba(24,28,36,.18)', borderRadius: '12px', padding: '18px 14px', textAlign: 'center', background: '#FAFBFD'}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="var(--ink)" strokeWidth="1.8" style={{marginBottom: '5px'}}><path d="M12 16V4" /><path d="m6 10 6-6 6 6" /><path d="M4 20h16" /></svg><div style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '12px'}}>Reel_v2.mp4</div><div style={{fontSize: '10.5px', color: 'var(--ink-soft)', marginTop: '2px'}}>in review</div></div><div style={{display: 'flex', justifyContent: 'space-between', fontSize: '11.5px'}}><span style={{color: 'var(--ink-soft)'}}>revisions</span><span style={{fontWeight: '600'}}>1 of 2 used</span></div><div style={{display: 'flex', gap: '4px'}}><div style={{flex: '1', height: '6px', borderRadius: '3px', background: 'var(--neon-deep)'}}></div><div style={{flex: '1', height: '6px', borderRadius: '3px', background: 'rgba(18,21,28,.12)'}}></div></div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>03</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Deliver</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Upload and get approved</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Revisions are counted against what was agreed — no quiet scope creep later.</p>
              </div>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: '1px solid var(--hairline)'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '9px'}}><div style={{fontSize: '11.5px', color: 'var(--ink-soft)'}}>Payment</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: 'var(--neon)'}}></span>Agreed · ₹48,000</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: 'var(--neon)'}}></span>Content approved</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: 'var(--neon)'}}></span>Payout sent</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px', color: 'var(--ink-soft)'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: '#fff', border: '1.5px solid var(--hairline)'}}></span>Paid · 14 Aug</div><div style={{marginTop: '4px', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '24px'}}>₹48,000</div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>04</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Get paid</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Watch payment move</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Live status from agreed to paid, visible to both sides. Nobody chases anyone.</p>
              </div>
            </div>
          </div>
        </section>

        <div style={{height: 'clamp(48px,6vw,88px)'}}></div>



        {/* INSIDE GUAPD MOSAIC */}
        <section className="mos-sec sr" style={{position: 'relative', background: '#12151C', width: '100%', padding: 'clamp(80px,10vw,140px) 0', overflow: 'hidden', marginTop: '0'}}>
          <div aria-hidden="true" style={{position: 'absolute', left: '50%', top: '0', transform: 'translateX(-50%)', width: '900px', height: '900px', background: 'radial-gradient(circle,rgba(184,229,82,.10),transparent 65%)', pointerEvents: 'none'}}></div>
          <div style={{position: 'relative', maxWidth: '1200px', margin: '0 auto', paddingInline: '24px'}}>
            <div style={{textAlign: 'center', maxWidth: '560px', margin: '0 auto clamp(36px,4.5vw,52px)'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'rgba(243,244,238,.55)'}}>Inside guapd</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.035em', lineHeight: '1.05', fontSize: 'clamp(28px,3.6vw,44px)', margin: '12px 0 0', color: '#F3F4EE'}}>Built for how deals <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400', color: 'var(--lime)'}}>actually happen</span></h2>
            </div>
            <div className="mos-grid" style={{display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gridTemplateRows: '1.9fr 1fr 1.6fr', gridTemplateAreas: '\'a a b\' \'c d b\' \'c d e\'', gap: '28px', height: 'clamp(520px,62vw,760px)'}}>
              <div className="mos-cell" data-mos style={{gridArea: 'a', transitionDelay: '0s'}}><img src="/landing/chatgpt-image-aug-18-2026-08-35-08-am.webp" alt="Two glass panels showing brand-side campaign command center and creator-side dashboard" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 18%'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'b', transitionDelay: '.08s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-14-48-pm.webp" alt="Glass panel showing mobile campaign overview" style={{width: '100%', height: '100%', objectFit: 'cover'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'c', transitionDelay: '.16s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-46-01-pm.webp" alt="Phone showing creator dashboard with new opportunities, active deal, and payment received" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 45%'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'd', transitionDelay: '.24s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-48-11-pm-0df98008.webp" alt="Glass panel showing deliverables list" style={{width: '100%', height: '100%', objectFit: 'cover'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'e', transitionDelay: '.32s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-31-30-pm.webp" alt="Glass panel showing campaign overview dashboard" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 65%'}} decoding="async" loading="lazy" /></div>
            </div>
          </div>
        </section>

        {/* SPLIT EDITORIAL: BLACK / WHITE */}
        <section className="sr" style={{position: 'relative', overflow: 'hidden', margin: 'clamp(24px,3vw,44px) 0 clamp(56px,6vw,88px)'}}>
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', minHeight: 'clamp(460px,60vw,640px)'}}>
            <div style={{background: '#12151C', display: 'flex', flexDirection: 'column', alignItems: 'flex-end', justifyContent: 'center', textAlign: 'right', padding: 'clamp(28px,5vw,64px) clamp(36px,6vw,88px)', gap: '20px'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.04em', lineHeight: '1.02', fontSize: 'clamp(28px,3.8vw,48px)', color: '#F3F4EE', margin: '0'}}>For <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>brands</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: 'clamp(14px,1.4vw,16px)', lineHeight: '1.6', color: '#9EA096', maxWidth: '340px', margin: '0'}}>Post offers, track responses, and see spend against every creator.</p>
              <a href="/brands" style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '13.5px', color: '#F3F4EE', background: 'transparent', border: '1.5px solid rgba(243,244,238,.4)', borderRadius: '999px', padding: '11px 22px', display: 'inline-flex', alignItems: 'center', gap: '6px', textDecoration: 'none'}}>Explore for brands <span aria-hidden="true">&rarr;</span></a>
            </div>
            <div style={{background: '#FFFFFF', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', justifyContent: 'center', textAlign: 'left', padding: 'clamp(28px,5vw,64px) clamp(36px,6vw,88px)', gap: '20px', border: '1.5px solid rgba(18,21,28,.14)'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.04em', lineHeight: '1.02', fontSize: 'clamp(28px,3.8vw,48px)', color: '#12151C', margin: '0'}}>For <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>creators</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: 'clamp(14px,1.4vw,16px)', lineHeight: '1.6', color: '#565C68', maxWidth: '340px', margin: '0'}}>Accept, counter, deliver, and get paid &mdash; without a single DM.</p>
              <a href="/creators" style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '13.5px', color: '#12151C', background: 'transparent', border: '1.5px solid rgba(18,21,28,.3)', borderRadius: '999px', padding: '11px 22px', display: 'inline-flex', alignItems: 'center', gap: '6px', textDecoration: 'none'}}>Explore for creators <span aria-hidden="true">&rarr;</span></a>
            </div>
          </div>
          <div style={{position: 'absolute', left: '50%', top: 'clamp(28px,5vw,64px)', bottom: 'clamp(28px,5vw,64px)', width: '1px', background: 'var(--lime)', transform: 'translateX(-.5px)'}}></div>
          <div style={{position: 'absolute', left: '50%', bottom: 'clamp(22px,3.5vw,40px)', transform: 'translateX(-50%)', background: '#12151C', padding: '6px 18px', fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: 'clamp(17px,1.8vw,22px)', color: '#F3F4EE', whiteSpace: 'nowrap'}}>one deal room</div>
        </section>

  



        {/* ============ CREATOR SIDE SHOWCASE ============ */}
        {/* ============ GLASS PANEL SHOWCASE (Built for creators) ============ */}
        <section style={{position: 'relative', background: '#fff', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)', overflow: 'hidden'}}>
          <div style={{position: 'relative', maxWidth: '1200px', margin: '0 auto', borderRadius: '32px', overflow: 'hidden', boxShadow: '0 20px 40px -30px rgba(40,45,25,.18)'}}>
            <img src="/landing/rectangle-84.webp" alt="Creator dashboard shown as glass panels — creator profile, opportunities, active deals, payment status" style={{width: '80%', height: 'auto', display: 'block', marginLeft: '-24px', filter: 'saturate(0.9) contrast(1.08) brightness(1.02)'}} decoding="async" loading="lazy" />
            <div aria-hidden="true" style={{position: 'absolute', top: '0', left: '0', width: '80%', height: '100%', background: 'linear-gradient(160deg,rgba(80,140,230,0.14),rgba(80,140,230,0.03) 60%)', mixBlendMode: 'multiply', pointerEvents: 'none'}}></div>
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', right: '0', width: '46%', background: 'linear-gradient(to left,#fff 0%,#fff 55%,rgba(255,255,255,0) 100%)', pointerEvents: 'none'}}></div>
            <div style={{position: 'absolute', top: '50%', right: '6%', transform: 'translateY(-50%)', width: 'min(30%,360px)', minWidth: '220px', textAlign: 'left'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Built for you</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(30px,3.1vw,44px)', margin: '12px 0 0', color: '#12151C'}}>Your whole hustle, <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>organized.</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: '#565C68', margin: '16px 0 0', maxWidth: '30ch'}}>Your profile, open opportunities, active deals and payment status — all tracked in one dashboard, so nothing slips through DMs.</p>
            </div>
          </div>
        </section>

        {/* SCROLL EXPAND MASCOT */}
        <section id="expandSection" style={{position: 'relative', height: '220vh'}}>
          <div id="expandPin" style={{position: 'absolute', top: '0', left: '0', width: '100%', height: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', overflow: 'hidden'}}>
            <img id="bgImg" src="/landing/hero-outer-bg.webp" alt="" style={{position: 'absolute', inset: '0', width: '100%', height: '100%', objectFit: 'cover', willChange: 'opacity'}} decoding="async" />
            <img id="expandImg" src="/landing/hero-inner-mascot.webp" alt="guapd" style={{position: 'relative', zIndex: '1', borderRadius: '24px', boxShadow: '0 30px 70px -20px rgba(20,22,10,.35)', objectFit: 'cover', willChange: 'width,height'}} decoding="async" />
          </div>
        </section>


        {/* FOUR REASONS — single bounded container, spaced cards */}
        <section style={{padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)'}}>
        <div className="gx" style={{background: '#fff', border: '1px solid var(--hairline)', borderRadius: '36px', boxShadow: '0 40px 90px -50px rgba(40,45,25,.3)', padding: 'clamp(44px,5.5vw,72px) clamp(24px,4vw,48px)'}}>
          <div style={{textAlign: 'center', maxWidth: '560px', margin: '0 auto clamp(44px,5.5vw,64px)'}}>
            <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>One connected system</span>
            <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.035em', lineHeight: '1.05', fontSize: 'clamp(30px,4vw,52px)', margin: '12px 0 0', color: 'var(--ink)'}}>Everything, <span className="t-accent" style={{fontSize: '1.05em'}}>in one place</span></h2>
          </div>
          <div className="stack-outer" style={{position: 'relative', height: '1900px', marginBottom: '70px'}}>
          <div className="stack-pin" style={{position: 'sticky', top: '96px', height: 'auto', overflow: 'visible'}}>

          {/* 01 — timeline that fills */}
          <div data-stack-card="0" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(135deg,#EFFAF5 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)'}}>
            <div>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '11px', color: 'var(--ink)'}}>01</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>One thread</span></div>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0', maxWidth: '360px'}}>One thread, from offer to <span className="t-accent">payout</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '360px', margin: '16px 0 0'}}>Every deal moves through the same four steps, tracked automatically from the first offer to the final payout.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Auto-tracked</span>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>No manual updates</span>
              </div>
            </div>
            <div className="lift" style={{width: '100%'}}>
              <div style={{background: '#fff', borderRadius: '22px', border: '1px solid var(--hairline)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', padding: 'clamp(24px,3vw,28px)', display: 'flex', flexDirection: 'column', gap: '10px'}}>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#F3FBF6', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '600'}}><span>&#10003; Offer</span></span>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#F3FBF6', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '600'}}><span>&#10003; Agreed</span></span>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#F6FAFE', border: '1px solid var(--hairline)', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '600', color: 'var(--ink-soft)'}}><span>&#8226; Delivered</span></span>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#fff', border: '1px dashed var(--hairline)', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', color: 'var(--ink-faint)'}}><span>Paid</span><span>&#8377;48,000</span></span>
              </div>
            </div>
          </div>

          </div>

          {/* 02 — split-flap board */}
          <div data-stack-card="1" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(225deg,#EFF6FD 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)'}}>
            <div style={{order: '1'}}>
              <div style={{padding: 'clamp(24px,3vw,32px)', display: 'flex', flexDirection: 'column', gap: '12px', background: '#fff', borderRadius: '20px', border: '1px solid var(--hairline)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}>
                <span className="t-meta" style={{color: 'var(--ink-faint)'}}>Deal &middot; #GD-2506</span>
                <div style={{height: '52px', overflow: 'hidden'}}>
                  <div style={{animation: 'flapRoll 9s ease-in-out infinite'}}>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '30px', color: 'var(--ink)'}}>Sent</div>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '30px', color: 'var(--ink)'}}>Countered</div>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '30px', color: 'var(--ink)'}}>Agreed</div>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '30px', color: 'var(--ink)'}}>Paid</div>
                  </div>
                </div>
                <div style={{display: 'flex', gap: '6px', marginTop: '6px'}}>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'var(--neon-deep)'}}></div>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'rgba(26,27,22,.14)', animation: 'stepLight2 9s ease-in-out infinite'}}></div>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'rgba(26,27,22,.14)', animation: 'stepLight3 9s ease-in-out infinite'}}></div>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'rgba(26,27,22,.14)', animation: 'stepLight4 9s ease-in-out infinite'}}></div>
                </div>
                <div style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '26px', color: 'var(--ink)', marginTop: '10px'}}>&#8377;48,000</div>
              </div>
            </div>
            <div style={{order: '2'}}>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '11px', color: 'var(--ink)'}}>02</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>Always current</span></div>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0', maxWidth: '340px'}}>Always know where things <span className="t-accent">stand</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '380px', margin: '16px 0 0'}}>No guessing, no chasing. Every state change is recorded the moment it happens.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Timestamped</span>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Always live</span>
              </div>
            </div>
          </div>

          </div>

          {/* 03 — flipping problem/fix tiles */}
          <div data-stack-card="2" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(135deg,#F5F0FD 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)', perspective: '1200px'}}>
            <div>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '11px', color: 'var(--ink)'}}>03</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>Problem &rarr; fix</span></div>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0'}}>Three headaches, <span className="t-accent">gone</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '340px', margin: '16px 0 0'}}>The three things brands and creators complain about most, solved by design.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Solved by design</span>
              </div>
            </div>
            <div style={{display: 'flex', flexDirection: 'column', gap: '12px'}}>
              <div style={{position: 'relative', height: '68px', transformStyle: 'preserve-3d', animation: 'flipTile 9s cubic-bezier(.6,0,.3,1) infinite'}}>
                <div style={{position: 'absolute', inset: '0', background: '#fff', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-faint)'}}>Problem</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Scattered DMs</span></div>
                <div style={{position: 'absolute', inset: '0', background: '#FBF8FE', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-soft)'}}>guapd</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>One deal inbox</span></div>
              </div>
              <div style={{position: 'relative', height: '68px', transformStyle: 'preserve-3d', animation: 'flipTile 9s cubic-bezier(.6,0,.3,1) .5s infinite'}}>
                <div style={{position: 'absolute', inset: '0', background: '#fff', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-faint)'}}>Problem</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Lost terms</span></div>
                <div style={{position: 'absolute', inset: '0', background: '#FBF8FE', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-soft)'}}>guapd</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Locked &amp; timestamped</span></div>
              </div>
              <div style={{position: 'relative', height: '68px', transformStyle: 'preserve-3d', animation: 'flipTile 9s cubic-bezier(.6,0,.3,1) 1s infinite'}}>
                <div style={{position: 'absolute', inset: '0', background: '#fff', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-faint)'}}>Problem</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Chasing payment</span></div>
                <div style={{position: 'absolute', inset: '0', background: '#FBF8FE', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-soft)'}}>guapd</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Live payout status</span></div>
              </div>
            </div>
          </div>

          </div>

          {/* 04 — card sorter */}
          <div data-stack-card="3" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(225deg,#FBFAEF 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)'}}>
            <div style={{position: 'relative', width: '100%', height: '270px', justifySelf: 'center', order: '1'}}>
              <div style={{position: 'absolute', left: '0', right: '0', top: '0', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) infinite'}}><span style={{fontWeight: '700'}}>Groww</span><span style={{color: 'var(--ink-faint)'}}>&#8377;45,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '56px', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .12s infinite'}}><span style={{fontWeight: '700'}}>Zerodha</span><span style={{color: 'var(--ink-faint)'}}>&#8377;60,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '112px', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .24s infinite'}}><span style={{fontWeight: '700'}}>Fi Money</span><span style={{color: 'var(--ink-faint)'}}>&#8377;35,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '168px', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .36s infinite'}}><span style={{fontWeight: '700'}}>CRED</span><span style={{color: 'var(--ink-faint)'}}>&#8377;52,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '224px', background: '#FBFAEF', border: '1.5px solid var(--neon-deep)', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', borderRadius: '12px', padding: '12px 14px', display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: '700', color: 'var(--ink)', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .48s infinite'}}><span>4 need you today</span><span style={{color: 'var(--ink)'}}>&rarr;</span></div>
            </div>
            <div style={{order: '2'}}>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: '11px', color: 'var(--ink)'}}>04</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>One queue</span></div>
              <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '800', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0', maxWidth: '340px'}}>Every deal, one <span className="t-accent">queue</span>.</h3>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '380px', margin: '16px 0 0'}}>Every campaign lands in the same queue, ranked by what actually needs your attention today.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Ranked for you</span>
              </div>
            </div>
          </div>

          </div>
          </div>
          </div>
        </div>
        </section>

        {/* ============ APP SHOWCASE ============ */}
        <section style={{position: 'relative', width: '100vw', left: '50%', right: '50%', marginLeft: '-50vw', marginRight: '-50vw', overflow: 'hidden', marginTop: 'clamp(48px,6vw,88px)'}}>
          <img src="/landing/app-showcase-clouds.webp" alt="guapd deals dashboard with offer accepted, campaign live, deliverable approved, payment received, and earnings received notifications" style={{width: '100%', height: 'auto', display: 'block'}} decoding="async" loading="lazy" />
          <div style={{position: 'absolute', left: 'calc(clamp(20px,5vw,72px) + 120px)', top: '0', bottom: '0', width: '26%', display: 'flex', alignItems: 'center', justifyContent: 'flex-start', background: 'transparent'}}>
            <div style={{textAlign: 'left'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Your deals, your dashboard</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.04', fontSize: 'clamp(28px,3.8vw,48px)', margin: '12px 0 0', color: 'var(--ink)'}}>Everything, always in <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>view</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.5', color: 'var(--ink-soft)', margin: '14px 0 0', maxWidth: '320px'}}>Campaigns, earnings, and reviews — all live in one dashboard.</p>
              <div style={{marginTop: '24px'}}><div className="magnet"><a href="/signup/brand" className="lp-btn">Get early access</a></div></div>
            </div>
          </div>
        </section>

        {/* PRODUCT SHOWCASE */}
        <section style={{padding: 'clamp(64px,7vw,100px) clamp(20px,5vw,72px) clamp(32px,4vw,52px)'}}>

          <div className="gx" style={{textAlign: 'center'}}>
            <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Deals on guapd</span>
            <h2 className="t-title" style={{fontSize: 'clamp(28px,3.8vw,48px)', margin: '10px 0 clamp(20px,2.4vw,30px)'}}>Recent deals on <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>guapd</span></h2>
            <div className="sf-exprow" style={{gap: '20px'}}>
              <div className="sf-exp">
                <div className="sf-vid"><span style={{position: 'absolute', left: '11px', top: '11px', zIndex: '3', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '9.5px', letterSpacing: '.05em', textTransform: 'uppercase', background: 'rgba(255,255,255,.92)', color: 'var(--ink)', borderRadius: '999px', padding: '3px 9px'}}>Reel</span><span className="sf-play"><svg width="15" height="15" viewBox="0 0 24 24" fill="#E8FF66"><path d="M8 5v14l11-7z" /></svg></span><div className="sf-vlab">Skincare routine</div></div>
                <div className="sf-side"><div className="sf-side-in"><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', letterSpacing: '-0.01em', lineHeight: '1.25', color: 'var(--ink)'}}>Skincare routine</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--ink-faint)', marginTop: '6px'}}>Nykaa · Jun 2026</div><div style={{marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: '9px'}}><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Views</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>2.4M</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Engagement</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>8.1%</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Saves</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>34K</b></div></div></div></div>
              </div>
              <div className="sf-exp">
                <div className="sf-vid"><span style={{position: 'absolute', left: '11px', top: '11px', zIndex: '3', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '9.5px', letterSpacing: '.05em', textTransform: 'uppercase', background: 'rgba(255,255,255,.92)', color: 'var(--ink)', borderRadius: '999px', padding: '3px 9px'}}>Reel</span><span className="sf-play"><svg width="15" height="15" viewBox="0 0 24 24" fill="#E8FF66"><path d="M8 5v14l11-7z" /></svg></span><div className="sf-vlab">Goa on ₹5k</div></div>
                <div className="sf-side"><div className="sf-side-in"><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', letterSpacing: '-0.01em', lineHeight: '1.25', color: 'var(--ink)'}}>Goa on ₹5k</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--ink-faint)', marginTop: '6px'}}>MakeMyTrip · May 2026</div><div style={{marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: '9px'}}><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Views</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>1.1M</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Engagement</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>6.4%</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Saves</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>21K</b></div></div></div></div>
              </div>
              <div className="sf-exp">
                <div className="sf-vid"><span style={{position: 'absolute', left: '11px', top: '11px', zIndex: '3', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '9.5px', letterSpacing: '.05em', textTransform: 'uppercase', background: 'rgba(255,255,255,.92)', color: 'var(--ink)', borderRadius: '999px', padding: '3px 9px'}}>Reel</span><span className="sf-play"><svg width="15" height="15" viewBox="0 0 24 24" fill="#E8FF66"><path d="M8 5v14l11-7z" /></svg></span><div className="sf-vlab">Get ready with me</div></div>
                <div className="sf-side"><div className="sf-side-in"><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', letterSpacing: '-0.01em', lineHeight: '1.25', color: 'var(--ink)'}}>Get ready with me</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--ink-faint)', marginTop: '6px'}}>Sugar · May 2026</div><div style={{marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: '9px'}}><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Views</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>1.7M</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Engagement</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>7.2%</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Saves</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>28K</b></div></div></div></div>
              </div>
              <div className="sf-exp">
                <div className="sf-vid"><span style={{position: 'absolute', left: '11px', top: '11px', zIndex: '3', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '9.5px', letterSpacing: '.05em', textTransform: 'uppercase', background: 'rgba(255,255,255,.92)', color: 'var(--ink)', borderRadius: '999px', padding: '3px 9px'}}>Reel</span><span className="sf-play"><svg width="15" height="15" viewBox="0 0 24 24" fill="#E8FF66"><path d="M8 5v14l11-7z" /></svg></span><div className="sf-vlab">SIP explained</div></div>
                <div className="sf-side"><div className="sf-side-in"><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', letterSpacing: '-0.01em', lineHeight: '1.25', color: 'var(--ink)'}}>SIP explained</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--ink-faint)', marginTop: '6px'}}>Groww · Apr 2026</div><div style={{marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: '9px'}}><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Views</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>1.1M</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Engagement</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>6.4%</b></div><div className="sf-srow"><span style={{fontFamily: 'var(--font-ui)', fontSize: '10px', letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Saves</span><b style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '15px', color: 'var(--ink)'}}>22K</b></div></div></div></div>
              </div>
            </div>
          </div>
        </section>

        {/* CAMPAIGNS */}
        <section id="campaigns" style={{background: 'var(--card)', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)'}}>
          <div className="gx">
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.035em', lineHeight: '1.04', textAlign: 'center', fontSize: 'clamp(28px,3.8vw,48px)', margin: '0 0 40px', color: 'var(--ink)'}}>Featured <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>campaigns</span></h2>
          {campaigns.map((p, i) => (
            <div className="pcard" data-pcard style={{top: '{p.top}px', marginBottom: '28px', height: '85vh', maxWidth: '1080px', marginLeft: 'auto', marginRight: 'auto', padding: 'clamp(16px,2vw,32px)', background: 'var(--card)', border: '1px solid var(--hairline)', borderRadius: '40px', boxShadow: 'var(--sh-2)', position: 'sticky'}}>
              <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '16px', flexWrap: 'wrap'}}>
                <div style={{display: 'flex', alignItems: 'center', gap: '20px'}}>
                  <span className="t-meta" style={{color: 'var(--sec-ink)', width: '28px'}}>{p.num}</span>
                  <div>
                    <div className="t-meta" style={{color: 'var(--ink-faint)'}}>Brand &middot; {p.category}</div>
                    <div style={{color: 'var(--ink)', fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.02em', fontSize: 'clamp(18px,2.2vw,26px)', marginTop: '4px'}}>{p.name}</div>
                  </div>
                </div>
                <a href="#" className="g-btn-secondary" style={{padding: '11px 26px'}}>{p.deliverables} deliverables</a>
              </div>
              <div style={{display: 'flex', gap: '24px', marginTop: '24px', height: 'calc(100% - 100px)'}}>
                <div aria-hidden="true" data-placeholder="Campaign image" style={{...{flex: '1', minWidth: '0', height: '100%'}, background: 'var(--paper-2, #EDF0F5)', borderRadius: '28px'}} />
                <div aria-hidden="true" data-placeholder="Campaign image" style={{...{flex: '1', minWidth: '0', height: '100%'}, background: 'var(--paper-2, #EDF0F5)', borderRadius: '28px'}} />
                <div aria-hidden="true" data-placeholder="Campaign image" style={{...{flex: '1', minWidth: '0', height: '100%'}, background: 'var(--paper-2, #EDF0F5)', borderRadius: '28px'}} />
              </div>
            </div>
          ))}
          </div>
        </section>




        {/* ============ FAQ ============ */}
        {/* CREATORS & BRANDS (borrowed from For Brands page) */}
        <section className="sr" style={{padding: 'clamp(36px,4vw,56px) clamp(20px,5vw,72px)'}}>
          <div className="gx">
            <div style={{textAlign: 'center', maxWidth: '620px', margin: '0 auto clamp(36px,4.5vw,56px)'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Creators on guapd</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.035em', lineHeight: '1.04', fontSize: 'clamp(28px,3.8vw,48px)', margin: '12px 0 0', color: 'var(--ink)'}}>Find vetted <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>creators</span></h2>
            </div>
            <div style={{display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 'clamp(16px,2.4vw,34px)', maxWidth: '980px', margin: '0 auto'}}>
              <div className="card" style={{background: 'var(--card)', border: '1.2px solid var(--hairline)', borderRadius: '24px', padding: '14px', boxShadow: '0 22px 50px -28px rgba(40,45,25,.34)'}}><div style={{width: '100%', height: 'auto', aspectRatio: '1/1', display: 'block', borderRadius: '16px', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><div style={{padding: '16px 6px 6px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.01em', color: 'var(--ink)'}}>@aisha.fin</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', marginTop: '10px'}}><span style={{fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', color: 'var(--ink)', background: '#FFFFFF', border: '1px solid var(--hairline)', borderRadius: 'var(--radius-pill)', padding: '3px 10px'}}>Finance</span><span style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', color: 'var(--ink-faint)'}}>180K followers</span></div></div></div>
              <div className="card" style={{background: 'var(--card)', border: '1.2px solid var(--hairline)', borderRadius: '24px', padding: '14px', boxShadow: '0 22px 50px -28px rgba(40,45,25,.34)'}}><div style={{width: '100%', height: 'auto', aspectRatio: '1/1', display: 'block', borderRadius: '16px', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><div style={{padding: '16px 6px 6px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.01em', color: 'var(--ink)'}}>@rohan.tech</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', marginTop: '10px'}}><span style={{fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', color: 'var(--ink)', background: '#FFFFFF', border: '1px solid var(--hairline)', borderRadius: 'var(--radius-pill)', padding: '3px 10px'}}>Tech</span><span style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', color: 'var(--ink-faint)'}}>92K followers</span></div></div></div>
              <div className="card" style={{background: 'var(--card)', border: '1.2px solid var(--hairline)', borderRadius: '24px', padding: '14px', boxShadow: '0 22px 50px -28px rgba(40,45,25,.34)'}}><div style={{width: '100%', height: 'auto', aspectRatio: '1/1', display: 'block', borderRadius: '16px', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><div style={{padding: '16px 6px 6px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.01em', color: 'var(--ink)'}}>@priya.career</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', marginTop: '10px'}}><span style={{fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', color: 'var(--ink)', background: '#FFFFFF', border: '1px solid var(--hairline)', borderRadius: 'var(--radius-pill)', padding: '3px 10px'}}>Careers</span><span style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', color: 'var(--ink-faint)'}}>95K followers</span></div></div></div>
              <div className="card" style={{background: 'var(--card)', border: '1.2px solid var(--hairline)', borderRadius: '24px', padding: '14px', boxShadow: '0 22px 50px -28px rgba(40,45,25,.34)'}}><div style={{width: '100%', height: 'auto', aspectRatio: '1/1', display: 'block', borderRadius: '16px', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><div style={{padding: '16px 6px 6px'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', letterSpacing: '-0.01em', color: 'var(--ink)'}}>@maya.money</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', marginTop: '10px'}}><span style={{fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', color: 'var(--ink)', background: '#FFFFFF', border: '1px solid var(--hairline)', borderRadius: 'var(--radius-pill)', padding: '3px 10px'}}>Lifestyle</span><span style={{fontFamily: 'var(--font-ui)', fontSize: '12.5px', color: 'var(--ink-faint)'}}>210K followers</span></div></div></div>
            </div>
          </div>
        </section>

        {/* BRANDS WE WORK WITH (borrowed from For Brands page) */}
        <section className="sr" style={{padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)'}}>
          <div style={{maxWidth: '980px', margin: '0 auto', border: '1.2px solid var(--hairline)', borderRadius: '24px', background: 'var(--card)', boxShadow: '0 22px 50px -34px rgba(40,45,25,.3)', padding: 'clamp(32px,4.5vw,56px) clamp(20px,4vw,48px)', textAlign: 'center'}}>
            <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Brands we work with</span>
      <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.035em', lineHeight: '1.04', fontSize: 'clamp(28px,3.8vw,48px)', margin: '10px 0 clamp(24px,3.2vw,34px)', color: 'var(--ink)'}}>Brands you <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>know</span></h2>
            <div id="brandPillRow" className="brand-pill-row" style={{display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', gap: '14px', overflow: 'hidden'}}>
              <div className="brand-pill" style={{display: 'flex', alignItems: 'center', gap: '11px', background: 'var(--card)', border: '1px solid var(--frost-edge)', borderRadius: '16px', padding: '12px 18px 12px 12px', boxShadow: '0 12px 30px -22px rgba(40,45,25,.3)', flexShrink: '0'}}><div style={{width: '38px', height: '38px', display: 'block', flexShrink: '0', borderRadius: '50%', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Groww</span></div>
              <div className="brand-pill" style={{display: 'flex', alignItems: 'center', gap: '11px', background: 'var(--card)', border: '1px solid var(--frost-edge)', borderRadius: '16px', padding: '12px 18px 12px 12px', boxShadow: '0 12px 30px -22px rgba(40,45,25,.3)', flexShrink: '0'}}><div style={{width: '38px', height: '38px', display: 'block', flexShrink: '0', borderRadius: '50%', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Zerodha</span></div>
              <div className="brand-pill" style={{display: 'flex', alignItems: 'center', gap: '11px', background: 'var(--card)', border: '1px solid var(--frost-edge)', borderRadius: '16px', padding: '12px 18px 12px 12px', boxShadow: '0 12px 30px -22px rgba(40,45,25,.3)', flexShrink: '0'}}><div style={{width: '38px', height: '38px', display: 'block', flexShrink: '0', borderRadius: '50%', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Fi Money</span></div>
              <div className="brand-pill" style={{display: 'flex', alignItems: 'center', gap: '11px', background: 'var(--card)', border: '1px solid var(--frost-edge)', borderRadius: '16px', padding: '12px 18px 12px 12px', boxShadow: '0 12px 30px -22px rgba(40,45,25,.3)', flexShrink: '0'}}><div style={{width: '38px', height: '38px', display: 'block', flexShrink: '0', borderRadius: '50%', border: '1px solid var(--hairline)', background: '#FFFFFF'}}></div><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>CRED</span></div>
            </div>
          </div>
        </section>
  



        <section style={{padding: 'clamp(32px,4vw,52px) clamp(20px,5vw,72px)'}}>
          <div className="sr gx" style={{background: 'var(--card)', borderRadius: '28px', border: '1px solid var(--hairline)', boxShadow: '0 24px 54px -36px rgba(40,45,25,.24)', padding: 'clamp(40px,5.5vw,56px) clamp(28px,5vw,48px)'}}>
            <div style={{textAlign: 'center', marginBottom: 'clamp(28px,3.6vw,42px)'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '800', letterSpacing: '-0.035em', lineHeight: '1.04', fontSize: 'clamp(28px,3.8vw,48px)', margin: '12px 0 0'}}>FAQ <span style={{fontFamily: '\'Instrument Serif\',serif', fontStyle: 'italic', fontWeight: '400'}}>answered</span></h2>
            </div>
            {faqs.map((f, i) => (
              <div className="faqitem" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} style={{display: 'grid', gridTemplateColumns: '56px 1fr 20px', borderTop: '1px solid var(--hairline)', padding: 'clamp(28px,3.4vw,36px) clamp(12px,1.6vw,18px)', borderRadius: '14px', cursor: 'pointer', transition: 'background .16s ease'}}>
                <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: '26px', color: 'var(--ink-faint)', lineHeight: '1', alignSelf: 'baseline'}}>{f.num}</span>
                <div style={{gridColumn: '2'}}>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(16px,1.7vw,18px)', letterSpacing: '-0.01em'}}>{f.q}</span>
                  {f.open && (<>
                    <p style={{fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '12px 0 0', maxWidth: '520px'}}>{f.a}</p>
                  </>)}
                </div>
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="var(--ink-faint)" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0', alignSelf: 'baseline'}}><path d={f.icon} /></svg>
              </div>
            ))}
          </div>
        </section>



        {/* VISION */}
        <section className="on-dark sr" style={{background: '#12151C', borderRadius: '28px', maxWidth: '1200px', margin: 'clamp(56px,6vw,88px) auto clamp(56px,6vw,88px)', padding: 'clamp(44px,5.5vw,64px) clamp(24px,4vw,44px)', textAlign: 'center'}}>
          <p style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: 'clamp(19px,2vw,24px)', lineHeight: '1.5', letterSpacing: '-0.01em', margin: '0', color: '#F3F4EE'}}>Soon, agents handle the busywork &mdash; you stay in <span style={{fontFamily: '\'Instrument Serif\',serif', fontStyle: 'italic', fontWeight: '400', color: 'var(--lime)'}}>control</span>.</p>
          <a href="#" style={{display: 'inline-block', marginTop: '14px', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '13.5px', color: '#9EA096'}}>See the vision &rarr;</a>
        </section>

        {/* ============ CREATOR SIDE SHOWCASE ============ */}



        {/* CONVERGE — two sides meet */}
        <section id="cvSec" style={{position: 'relative', width: '100%', height: '230vh', overflow: 'hidden'}}>
          <div id="cvPin" style={{position: 'absolute', top: '0', left: '0', width: '100%', height: '100vh', overflow: 'hidden'}}>
            <div className="cv-motion" style={{position: 'absolute', inset: '0'}}>
              <div id="cvBarLeft" style={{position: 'absolute', left: '0', top: '50%', width: '50vw', height: '6px', borderRadius: '3px', background: '#E8FF66', transformOrigin: 'left center'}}></div>
              <div id="cvBarRight" style={{position: 'absolute', right: '0', top: '50%', width: '50vw', height: '6px', borderRadius: '3px', background: '#E8FF66', transformOrigin: 'right center'}}></div>
              <div id="cvCircle" style={{position: 'absolute', left: '50%', top: '50%', width: '120px', height: '120px', borderRadius: '50%', background: '#E8FF66', marginLeft: '-60px', marginTop: '-60px'}}></div>
              <div style={{position: 'absolute', inset: '0', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                <div style={{position: 'relative', zIndex: '2', maxWidth: '560px', textAlign: 'center', padding: '0 24px'}}>
                  <div id="cvEyebrow" style={{color: '#12151C', fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', letterSpacing: '.14em', opacity: '0'}}>TWO SIDES</div>
                  <h2 id="cvHead" style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(28px,3.8vw,48px)', margin: '16px 0 0', color: '#12151C', opacity: '0'}}>Where brands and creators <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>guap.</span></h2>
                  <p id="cvSub" style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.6', color: '#12151C', maxWidth: '560px', margin: '16px auto 0', opacity: '0'}}>One flow for briefs, terms and payouts &mdash; built for both sides of the deal.</p>
                  <div id="cvBtn" style={{marginTop: '26px', display: 'inline-flex', opacity: '0'}}>
                    <span style={{display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#FFFFFF', border: '1px solid #12151C', color: '#12151C', borderRadius: '999px', padding: '13px 26px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '14px'}}>Book demo</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="cv-reduced" style={{display: 'none', position: 'absolute', inset: '0', alignItems: 'center', justifyContent: 'center'}}>
              <div style={{position: 'absolute', left: '50%', top: '50%', width: '120px', height: '120px', borderRadius: '50%', background: '#E8FF66', transform: 'translate(-50%,-50%) scale(30)'}}></div>
              <div style={{position: 'relative', zIndex: '2', maxWidth: '560px', textAlign: 'center', padding: '0 24px'}}>
                <div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', letterSpacing: '.14em', color: '#12151C'}}>TWO SIDES</div>
                <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(28px,3.8vw,48px)', margin: '16px 0 0', color: '#12151C'}}>Where brands and creators <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>meet.</span></h2>
                <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.6', color: '#12151C', maxWidth: '560px', margin: '16px auto 0'}}>One flow for briefs, terms and payouts &mdash; built for both sides of the deal.</p>
                <div style={{marginTop: '26px', display: 'inline-flex'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#FFFFFF', border: '1px solid #12151C', color: '#12151C', borderRadius: '999px', padding: '13px 26px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '14px'}}>Book demo</span>
                </div>
              </div>
            </div>
          </div>
        </section>

  

      </div>
    </div>
  )
}
