'use client'

import { useEffect, useState } from 'react'
import { initLandingEffects } from '@/app/landing-effects'
import BookDemoModal from '@/components/BookDemoModal'

/**
 * The landing page, ported from the "Landing - desktop" design export.
 *
 * Markup is generated by scripts/landing-convert-from-export.py — edit the
 * converter and re-run it rather than editing the JSX below, or the next port
 * silently drops the change.
 *
 * A client component because the design is scroll-driven throughout: pinned
 * sequences, a scrubbed card stack, count-ups and reveals, all of which need
 * the real scroll position. The choreography itself lives in landing-effects.ts,
 * transcribed from the export so the timings stay exactly as designed.
 *
 * The two data sets are the export's own. They are placeholder content — the
 * campaigns in particular name brands that are not ours — and are here so the
 * full page can be reviewed before deciding what to keep, hide or replace with
 * real data.
 */

const CAMPAIGNS = [
      { id:'lc1', num:'01', category:'Nextlevel Studio', name:'Summer Reel campaign', deliverables: 3, top: 96 },
      { id:'lc2', num:'02', category:'Aura Brand Identity', name:'Launch teaser', deliverables: 2, top: 124 },
      { id:'lc3', num:'03', category:'Solaris Digital', name:'Product spotlight', deliverables: 4, top: 152 }
    ]

/**
 * Answers carry JSX so they can link. Everything asserted here is checked
 * against the code: Instagram and YouTube are the two platforms the creator
 * profile offers, campaigns group deals for real, and the roster is vetted.
 *
 * Two things deliberately NOT claimed. Pricing: the revenue model is still an
 * open decision, and a homepage is the wrong place to pin it. Performance
 * measurement: content metrics need the Meta API, which is not built, so the
 * answer says what the deal record actually gives you and no more.
 */
// Exported so the mobile layout of this page answers identically.
export const FAQ: { q: string; a: React.ReactNode }[] = [
  {
    q: 'What is guapd?',
    a: (
      <>
        One place to run a brand and creator collaboration from start to finish: the offer,
        the negotiation, the deliverables, the approvals and the payment status. Everything
        that currently lives across WhatsApp, email and a spreadsheet lives on one deal instead.
      </>
    ),
  },
  {
    q: 'What types of businesses can use guapd?',
    a: (
      <>
        Any brand that works with creators directly rather than through an agency, from a
        founder running their first campaign to a marketing team running several a month.
        There is more detail on the <a href="/brands">brands page</a>, and creators can see
        their side on the <a href="/creators">creators page</a>.
      </>
    ),
  },
  {
    q: 'How does guapd work?',
    a: (
      <>
        You build a structured offer: deliverables, rate, timeline, revisions, usage rights
        and payment terms. The creator accepts, counters or declines. Once agreed, the terms
        are locked and everything that follows, the work, the approvals and the payment
        status, is tracked against that same deal.
      </>
    ),
  },
  {
    q: 'What platforms can I use guapd for?',
    a: (
      <>
        Instagram and YouTube today, including Reels, Stories and video. The deal itself is
        platform-agnostic, so anything you agree in writing can be run through it.
      </>
    ),
  },
  {
    q: 'How do I find the right creators for my brand?',
    a: (
      <>
        Every creator on guapd is vetted before they appear, so you are browsing people we
        have checked rather than an open directory. Many publish a shopfront with their
        packages and rates, so you can see what they offer before you make an offer. You can
        also bring a creator you already work with.
      </>
    ),
  },
  {
    q: 'How are payments managed?',
    a: (
      <>
        Payment terms are agreed in the offer itself, so there is no separate conversation
        about them later. The deal then tracks where the payment is, from invoice through to
        paid, and both sides see the same status. Nobody has to ask whether it went through.
      </>
    ),
  },
  {
    q: 'Can I run multiple campaigns at once?',
    a: (
      <>
        Yes. Campaigns group deals, so you can brief several creators from one place, send
        the offers together and see every deal in that campaign side by side, while each one
        stays its own agreement with its own terms.
      </>
    ),
  },
  {
    q: 'How will I know whether it is working?',
    a: (
      <>
        Every deal carries its own history: what was offered, what was agreed, when the work
        landed, how many revisions it took and when it was paid. Across campaigns that gives
        you a straight read on which collaborations run smoothly and who to work with again.
        Content performance reporting is not part of guapd yet.
      </>
    ),
  },
  {
    q: 'How do I get started?',
    a: (
      <>
        Brands can <a href="/signup/brand">create an account</a> or book a demo and we will
        walk through it against the campaigns you actually run. Creators can{' '}
        <a href="/signup/creator">join here</a>. Either way the first deal takes minutes.
      </>
    ),
  },
]

export default function LandingPageClient() {
  const [openFaq, setOpenFaq] = useState(0)
  const [demoOpen, setDemoOpen] = useState(false)

  useEffect(() => initLandingEffects(), [])

  // The export's own view model: the loop reads f.num/f.icon/f.open, so the
  // derived fields are built here rather than inlined into the markup.
  const campaigns = CAMPAIGNS
  const faqs = FAQ.map((f, i) => ({
    ...f,
    open: openFaq === i,
    num: String(i + 1).padStart(2, '0'),
    icon: openFaq === i ? 'M5 12h14' : 'M12 5v14M5 12h14',
  }))

  return (
    <div className="landing-page">
      <div style={{fontFamily: 'var(--font-ui)', color: 'var(--ink)', position: 'relative', overflowX: 'clip', background: '#fff'}}>

        <div id="scrollProgress" style={{position: 'fixed', top: '0', left: '0', height: '2px', width: '0%', background: 'var(--neon-deep)', zIndex: '200'}}></div>

        {/* NAV */}
        <div style={{position: 'sticky', top: '0', zIndex: '100', padding: '26px clamp(14px,4vw,28px) 0'}}>
    
        </div>

        {/* ============ CAMPAIGN DASHBOARD SHOWCASE (from For Brands) ============ */}
        <section style={{position: 'relative', width: '100vw', left: '50%', right: '50%', marginLeft: '-50vw', marginRight: '-50vw', marginTop: 'clamp(-96px,-8vw,-70px)', overflow: 'hidden', background: '#fff', zIndex: '0', paddingBottom: '40px'}}>
          <div style={{position: 'relative', overflow: 'hidden', width: '92%', margin: '0 auto'}}>
            <img src="/landing/gemini-generated-image-waw95uwaw95uwaw9.webp" alt="guapd campaign brief, creator, invoice and deliverable glass panel" style={{position: 'relative', top: '-145px', left: '0', width: '100%', height: 'auto', display: 'block', marginBottom: '-145px'}} decoding="async" width={1800} height={1344} />
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', left: '0', width: '8%', background: 'linear-gradient(to right,#fff 0%,rgba(255,255,255,0) 100%)', pointerEvents: 'none', zIndex: '1'}}></div>
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', right: '0', width: '8%', background: 'linear-gradient(to left,#fff 0%,rgba(255,255,255,0) 100%)', pointerEvents: 'none', zIndex: '1'}}></div>
          </div>
          <div style={{position: 'absolute', zIndex: '2', left: '14%', top: 'calc(8% + 105px)', width: 'min(58%,700px)', minWidth: '200px', textAlign: 'left'}}>
            <div aria-hidden="true" style={{position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)', width: '680px', height: '680px', borderRadius: '50%', background: 'radial-gradient(circle,rgba(255,255,255,0.85) 0%,rgba(255,255,255,0) 70%)', zIndex: '-1', pointerEvents: 'none'}}></div>
            <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.02', fontSize: 'clamp(44px,3.2vw,56px)', margin: '0', color: '#12151C'}}>The operating system<br />for <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>creator deals.</span></h2>
            <p style={{fontFamily: 'var(--font-ui)', fontSize: '16px', lineHeight: '1.55', color: '#565C68', margin: '22px 0 0', maxWidth: '44ch'}}>Brands and creators, in one shared space: offers, approvals, deliverables and payments, start to finish.</p>
            <button type="button" style={{marginTop: '28px', background: '#12151C', color: '#fff', border: 'none', borderRadius: '999px', padding: '12px 24px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '700', cursor: 'pointer'}}>Book demo</button>
          </div>
        </section>

        {/* HERO — animated headline + mascot + product visual */}
        <section id="top" style={{position: 'relative', overflow: 'visible', background: '#fff', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px) clamp(56px,6vw,88px)'}}>
          <div className="gx" style={{position: 'relative', textAlign: 'center', maxWidth: '760px'}}>
            <span className="hero-in" style={{'--hd': '0s', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '10.5px', letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--ink-faint)'}}>Brand deals, reinvented</span>
            <h1 className="hero-in" style={{'--hd': '.08s', fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.0', fontSize: 'clamp(34px,4.6vw,52px)', margin: '18px auto 0', maxWidth: '17ch', color: 'var(--ink)'}}>Creator deals without the <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>chaos.</span></h1>
            <p className="hero-in" style={{'--hd': '.16s', fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '34ch', margin: '18px auto 0'}}>One calm place to send offers, agree terms, deliver content, and track payment.</p>
            <div className="hero-in" style={{'--hd': '.24s', display: 'flex', justifyContent: 'center', marginTop: '26px'}}><div className="magnet"><button type="button" className="lp-btn" onClick={() => setDemoOpen(true)}>Book demo</button></div></div>
          </div>
        </section>
  

        {/* ============ GLASS PANEL SHOWCASE (Built for brands) ============ */}
        <section className="sr" style={{position: 'relative', background: '#fff', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)', overflow: 'hidden'}}>
          <div style={{position: 'relative', maxWidth: '1200px', margin: '0 auto', borderRadius: '32px', overflow: 'hidden', boxShadow: '0 20px 40px -30px rgba(40,45,25,.18)'}}>
            <img src="/landing/chatgpt-image-aug-18-2026-05-22-57-pm.webp" alt="Glass panels showing brand-side creator discovery, campaign management, approvals, and reporting" style={{width: '80%', height: 'auto', display: 'block', marginLeft: 'auto', filter: 'saturate(0.9) contrast(1.08) brightness(1.02)'}} decoding="async" loading="lazy" width={1672} height={941} />
            <div aria-hidden="true" style={{position: 'absolute', top: '0', right: '0', width: '80%', height: '100%', background: 'linear-gradient(200deg,rgba(80,140,230,0.14),rgba(80,140,230,0.03) 60%)', mixBlendMode: 'multiply', pointerEvents: 'none'}}></div>
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', left: '0', width: '34%', background: 'linear-gradient(to right,#fff 0%,#fff 55%,rgba(255,255,255,0) 100%)', pointerEvents: 'none'}}></div>
            <div style={{position: 'absolute', top: '50%', left: '9%', transform: 'translateY(-50%)', width: 'min(30%,360px)', minWidth: '220px', textAlign: 'left'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Built for you</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(30px,3.1vw,44px)', margin: '12px 0 0', color: '#12151C'}}>Every campaign, <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>on track.</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: '#565C68', margin: '16px 0 0', maxWidth: '30ch'}}>Discover creators, manage campaigns, approve deliverables and track reporting, all tracked in one dashboard.</p>
            </div>
          </div>
        </section>

        {/* MOSAIC IMAGE GRID */}
  


        {/* HOW IT WORKS — pinned, scroll-driven */}
        <section id="how" className="hw-sec">
          <div className="hw-pin">
            <div className="hw-tints">
              <div className="hw-tint" data-hw-tint="0" style={{background: '#E9F7F0'}}></div>
              <div className="hw-tint" data-hw-tint="1" style={{background: '#E7F1FC'}}></div>
              <div className="hw-tint" data-hw-tint="2" style={{background: '#F0EAFD'}}></div>
              <div className="hw-tint" data-hw-tint="3" style={{background: '#FCF6E4'}}></div>
            </div>
            <div className="hw-topbar" id="hwTopbar" style={{flexDirection: 'column', alignItems: 'flex-start', gap: '2px', transition: 'opacity .5s ease'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(28px,3.8vw,48px)', letterSpacing: '-.02em', lineHeight: '1.05', margin: '0'}}>How it <span className="t-accent">works</span></h2>
            </div>
            <div className="hw-clip">
            <div className="hw-inner">
              <div className="hw-grid">
                <div className="hw-stage">
            <div className="hw-card" data-hw-card="0" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>New brief</span><span>Draft</span></div>
              <div style={{display: 'flex', alignItems: 'center', gap: '18px', marginTop: 'clamp(18px,2.4vw,30px)'}}>
                <div style={{width: '64px', height: '64px', borderRadius: '50%', background: '#F2EEFC', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '19px', color: 'var(--sec-ink)', flexShrink: '0'}}>AR</div>
                <div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '24px', letterSpacing: '-.02em'}}>Ananya Rao</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)', marginTop: '3px'}}>@ananyarao · 180K followers</div></div>
              </div>
              <div style={{marginTop: 'clamp(16px,2.2vw,28px)', borderTop: '1px solid var(--hairline)'}}>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: '1px solid var(--hairline)', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>deliverables</span><span style={{fontWeight: '600'}}>1 Reel + 2 Stories</span></div>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: '1px solid var(--hairline)', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>rate</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '21px'}}>₹45,000</span></div>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: '1px solid var(--hairline)', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>live by</span><span style={{fontWeight: '600'}}>24 Aug</span></div>
                <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 0', borderBottom: 'none', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>payment</span><span style={{fontWeight: '600'}}>50% upfront · 50% on approval</span></div>
              </div>
              <div style={{flex: '1', minHeight: '12px'}}></div>
              <div style={{background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '17px', textAlign: 'center', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '17px'}}>Send offer</div>
            </div>
            <div className="hw-card" data-hw-card="1" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>Negotiation</span><span>3 messages</span></div>
              <div style={{flex: '1', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '16px', padding: 'clamp(16px,2.4vw,30px) 0'}}>
                <div style={{alignSelf: 'flex-end', maxWidth: '78%', background: '#EAF1FB', borderRadius: '20px 20px 6px 20px', padding: '15px 19px', fontFamily: 'var(--font-ui)', fontSize: '16px'}}>Offer · ₹45,000 for 1 Reel + 2 Stories<div style={{fontSize: '13px', color: 'var(--ink-soft)', marginTop: '5px'}}>brand · 10:04</div></div>
                <div style={{alignSelf: 'flex-start', maxWidth: '78%', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '20px 20px 20px 6px', padding: '15px 19px', fontFamily: 'var(--font-ui)', fontSize: '16px'}}>Counter · ₹50,000, usage rights 60 days<div style={{fontSize: '13px', color: 'var(--ink-soft)', marginTop: '5px'}}>creator · 10:26</div></div>
                <div style={{alignSelf: 'flex-end', maxWidth: '78%', background: '#EAF1FB', borderRadius: '20px 20px 6px 20px', padding: '15px 19px', fontFamily: 'var(--font-ui)', fontSize: '16px'}}>₹48,000 final, 45 days usage<div style={{fontSize: '13px', color: 'var(--ink-soft)', marginTop: '5px'}}>brand · 11:02</div></div>
              </div>
              <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '14px', background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '16px 24px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '17px'}}><span>Terms locked</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700'}}>₹48,000</span></div>
            </div>
            <div className="hw-card" data-hw-card="2" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>Deliverable</span><span>in review</span></div>
              <div style={{flex: '1', margin: 'clamp(16px,2.4vw,28px) 0', border: '1.5px dashed rgba(24,28,36,.2)', borderRadius: '24px', background: '#FBFCFD', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '10px'}}>
                <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="var(--ink)" strokeWidth="1.7"><path d="M12 16V4" /><path d="m6 10 6-6 6 6" /><path d="M4 20h16" /></svg>
                <div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '22px', letterSpacing: '-.02em'}}>Reel_v2.mp4</div>
                <div style={{fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)'}}>uploaded 18 Aug · 42 MB</div>
              </div>
              <div style={{display: 'flex', justifyContent: 'space-between', fontFamily: 'var(--font-ui)', fontSize: '16px'}}><span style={{color: 'var(--ink-soft)'}}>revisions</span><span style={{fontWeight: '600'}}>1 of 2 used</span></div>
              <div style={{display: 'flex', gap: '6px', marginTop: '12px'}}><div style={{flex: '1', height: '9px', borderRadius: '5px', background: 'var(--neon-deep)'}}></div><div style={{flex: '1', height: '9px', borderRadius: '5px', background: 'rgba(18,21,28,.12)'}}></div></div>
              <div style={{marginTop: '18px', fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)'}}>Approval due in 2 days, or it clears automatically.</div>
            </div>
            <div className="hw-card" data-hw-card="3" style={{background: '#fff', borderRadius: '32px', boxShadow: '0 46px 100px -50px rgba(40,45,25,.42)', padding: 'clamp(24px,2.8vw,44px)', display: 'flex', flexDirection: 'column'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontFamily: 'var(--font-ui)', fontSize: '14px', color: 'var(--ink-soft)'}}><span>Payment</span><span>escrow</span></div>
              <div style={{flex: '1', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '20px', padding: 'clamp(16px,2.4vw,26px) 0', fontFamily: 'var(--font-ui)', fontSize: '17px'}}>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0'}}></span>Terms agreed · ₹48,000</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0'}}></span>Content approved</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: 'var(--neon)', flexShrink: '0'}}></span>Payout released</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '14px', color: 'var(--ink-soft)'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: '#fff', border: '1.5px solid var(--hairline)', flexShrink: '0'}}></span>In your account · 14 Aug</div>
              </div>
              <div style={{borderTop: '1px solid var(--hairline)', paddingTop: '20px', display: 'flex', alignItems: 'baseline', justifyContent: 'space-between'}}>
                <span style={{fontFamily: 'var(--font-ui)', fontSize: '15px', color: 'var(--ink-soft)'}}>paid out</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(34px,4vw,50px)', letterSpacing: '-.03em'}}>₹48,000</span>
              </div>
            </div>
                </div>
                <div className="hw-copy">
            <div className="hw-text" data-hw-text="0">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>01</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Offer</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Send a structured brief</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Deliverables, rate, timeline and payment split, written down and agreed before any work starts.</p>
            </div>
            <div className="hw-text" data-hw-text="1">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>02</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Agree</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Lock the terms in writing</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Every offer and counter is timestamped. The final number becomes the contract both sides sign.</p>
            </div>
            <div className="hw-text" data-hw-text="2">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>03</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Deliver</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Upload, review, approve</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Revisions are counted against what was agreed, so scope stays where you left it.</p>
            </div>
            <div className="hw-text" data-hw-text="3">
              <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '13px', color: 'var(--ink)', flexShrink: '0'}}>04</span>
                <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Get paid</span>
              </div>
              <div style={{overflow: 'hidden', paddingBottom: '6px', marginTop: 'clamp(18px,2.4vw,28px)'}}>
                <h3 className="hw-head" style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-.03em', lineHeight: '1.08', margin: '0', maxWidth: '14ch'}}>Watch the money move</h3>
              </div>
              <p style={{fontFamily: 'var(--font-ui)', fontWeight: '400', fontSize: 'clamp(16px,1.15vw,18px)', lineHeight: '1.6', color: 'var(--ink-soft)', maxWidth: '30em', margin: 'clamp(14px,1.6vw,20px) 0 0'}}>Live status from agreed to paid, visible to both sides. Nobody has to chase anyone.</p>
            </div>
                </div>
              </div>
            </div>
            </div>
            <div className="hw-dots"><span className="hw-dot" data-hw-dot="0"></span><span className="hw-dot" data-hw-dot="1"></span><span className="hw-dot" data-hw-dot="2"></span><span className="hw-dot" data-hw-dot="3"></span></div>
            </div>
    
          <div className="hw-stack">
            <div className="sr" style={{maxWidth: '660px', margin: '0 auto clamp(20px,4vw,32px)'}}>
              <h2 className="t-title" style={{fontSize: 'clamp(28px,3.8vw,48px)', margin: '0'}}>How it works</h2>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: 'none'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '9px'}}><div style={{display: 'flex', justifyContent: 'space-between', fontSize: '11.5px', color: 'var(--ink-soft)'}}><span>New brief</span><span>Draft</span></div><div style={{display: 'flex', alignItems: 'center', gap: '11px'}}><div style={{width: '36px', height: '36px', borderRadius: '50%', background: '#F7F4FB', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '12px', color: 'var(--sec-ink)'}}>AR</div><div><div style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '13px'}}>Ananya Rao</div><div style={{fontSize: '10.5px', color: 'var(--ink-soft)'}}>@ananyarao · 180K</div></div></div><div style={{display: 'flex', justifyContent: 'space-between', paddingTop: '9px', borderTop: '1px solid var(--hairline)', fontSize: '12px'}}><span style={{color: 'var(--ink-soft)'}}>deliverable</span><span style={{fontWeight: '600'}}>1 Reel</span></div><div style={{display: 'flex', justifyContent: 'space-between', fontSize: '12px'}}><span style={{color: 'var(--ink-soft)'}}>rate</span><span style={{fontWeight: '700'}}>₹45,000</span></div><div style={{marginTop: '6px', background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '8px', textAlign: 'center', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '12px'}}>Send offer</div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>01</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Offer</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Send a structured brief</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Deliverables, rate, timeline, and payment split, written down before any work starts.</p>
              </div>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: '1px solid var(--hairline)'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '7px'}}><div style={{fontSize: '11.5px', color: 'var(--ink-soft)'}}>Negotiation</div><div style={{alignSelf: 'flex-end', background: '#F4F8FC', borderRadius: '12px 12px 3px 12px', padding: '7px 11px', fontSize: '11.5px'}}>Offer · ₹45,000</div><div style={{alignSelf: 'flex-start', background: '#fff', border: '1px solid var(--hairline)', borderRadius: '12px 12px 12px 3px', padding: '7px 11px', fontSize: '11.5px'}}>Counter · ₹50,000</div><div style={{alignSelf: 'flex-end', background: '#F4F8FC', borderRadius: '12px 12px 3px 12px', padding: '7px 11px', fontSize: '11.5px'}}>₹48,000 final</div><div style={{alignSelf: 'center', marginTop: '5px', background: 'var(--neon)', borderRadius: 'var(--radius-pill)', padding: '7px 13px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '11px'}}>Locked · ₹48,000</div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>02</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Agree</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Lock terms, in writing</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Every offer and counter is timestamped. The final number becomes the contract.</p>
              </div>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: '1px solid var(--hairline)'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '9px'}}><div style={{fontSize: '11.5px', color: 'var(--ink-soft)'}}>Deliverable</div><div style={{border: '1.5px dashed rgba(24,28,36,.18)', borderRadius: '12px', padding: '18px 14px', textAlign: 'center', background: '#FAFBFD'}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="var(--ink)" strokeWidth="1.8" style={{marginBottom: '5px'}}><path d="M12 16V4" /><path d="m6 10 6-6 6 6" /><path d="M4 20h16" /></svg><div style={{fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '12px'}}>Reel_v2.mp4</div><div style={{fontSize: '10.5px', color: 'var(--ink-soft)', marginTop: '2px'}}>in review</div></div><div style={{display: 'flex', justifyContent: 'space-between', fontSize: '11.5px'}}><span style={{color: 'var(--ink-soft)'}}>revisions</span><span style={{fontWeight: '600'}}>1 of 2 used</span></div><div style={{display: 'flex', gap: '4px'}}><div style={{flex: '1', height: '6px', borderRadius: '3px', background: 'var(--neon-deep)'}}></div><div style={{flex: '1', height: '6px', borderRadius: '3px', background: 'rgba(18,21,28,.12)'}}></div></div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>03</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Deliver</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Upload and get approved</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Revisions are counted against what was agreed, no quiet scope creep later.</p>
              </div>
            </div>
            <div className="sr" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '24px', padding: 'clamp(28px,5vw,40px) 0', borderTop: '1px solid var(--hairline)'}}>
              <div style={{width: 'min(100%,330px)', background: '#fff', borderRadius: '20px', boxShadow: '0 22px 48px -30px rgba(40,45,25,.3)', padding: '20px'}}><div style={{display: 'flex', flexDirection: 'column', gap: '9px'}}><div style={{fontSize: '11.5px', color: 'var(--ink-soft)'}}>Payment</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: 'var(--neon)'}}></span>Agreed · ₹48,000</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: 'var(--neon)'}}></span>Content approved</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: 'var(--neon)'}}></span>Payout sent</div><div style={{display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11.5px', color: 'var(--ink-soft)'}}><span style={{width: '14px', height: '14px', borderRadius: '50%', background: '#fff', border: '1.5px solid var(--hairline)'}}></span>Paid · 14 Aug</div><div style={{marginTop: '4px', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '24px'}}>₹48,000</div></div></div>
              <div>
                <div style={{display: 'flex', alignItems: 'center', gap: '12px'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '34px', height: '34px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '12.5px', color: 'var(--ink)', flexShrink: '0'}}>04</span>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '12.5px', letterSpacing: '.09em', textTransform: 'uppercase', color: 'var(--ink-soft)'}}>Get paid</span>
                </div>
                <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.035em', lineHeight: '1.14', margin: '14px 0 0'}}>Watch payment move</h3>
                <p style={{fontFamily: 'var(--font-ui)', fontWeight: '500', fontSize: '17px', lineHeight: '1.55', color: 'var(--ink)', margin: '12px 0 0'}}>Live status from agreed to paid, visible to both sides. Nobody chases anyone.</p>
              </div>
            </div>
          </div>
        </section>

        <div style={{height: 'clamp(48px,6vw,88px)'}}></div>



        {/* INSIDE GUAPD MOSAIC */}
        <section className="mos-sec sr" style={{position: 'relative', background: '#12151C', width: '100%', padding: 'clamp(80px,10vw,140px) 0', overflow: 'hidden', marginTop: '0'}}>
          <div aria-hidden="true" style={{position: 'absolute', left: '50%', top: '0', transform: 'translateX(-50%)', width: '900px', height: '900px', background: 'radial-gradient(circle,rgba(184,229,82,.10),transparent 65%)', pointerEvents: 'none'}}></div>
          <div style={{position: 'relative', maxWidth: '1200px', margin: '0 auto', paddingInline: '24px'}}>
            <div style={{textAlign: 'center', maxWidth: '560px', margin: '0 auto clamp(36px,4.5vw,52px)'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'rgba(243,244,238,.55)'}}>Inside guapd</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.035em', lineHeight: '1.05', fontSize: 'clamp(28px,3.6vw,44px)', margin: '12px 0 0', color: '#F3F4EE'}}>Built for how deals <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400', color: 'var(--lime)'}}>actually happen</span></h2>
            </div>
            <div className="mos-grid" style={{display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gridTemplateRows: '1.9fr 1fr 1.6fr', gridTemplateAreas: '\'a a b\' \'c d b\' \'c d e\'', gap: '28px', height: 'clamp(520px,62vw,760px)'}}>
              <div className="mos-cell" data-mos style={{gridArea: 'a', transitionDelay: '0s'}}><img src="/landing/chatgpt-image-aug-18-2026-08-35-08-am.webp" alt="Two glass panels showing brand-side campaign command center and creator-side dashboard" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 18%'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'b', transitionDelay: '.08s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-14-48-pm.webp" alt="Glass panel showing mobile campaign overview" style={{width: '100%', height: '100%', objectFit: 'cover'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'c', transitionDelay: '.16s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-46-01-pm.webp" alt="Phone showing creator dashboard with new opportunities, active deal, and payment received" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 45%'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'd', transitionDelay: '.24s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-48-11-pm-0df98008.webp" alt="Glass panel showing deliverables list" style={{width: '100%', height: '100%', objectFit: 'cover'}} decoding="async" loading="lazy" /></div>
              <div className="mos-cell" data-mos style={{gridArea: 'e', transitionDelay: '.32s'}}><img src="/landing/chatgpt-image-aug-18-2026-04-31-30-pm.webp" alt="Glass panel showing campaign overview dashboard" style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 65%'}} decoding="async" loading="lazy" /></div>
            </div>
          </div>
        </section>

        {/* SPLIT EDITORIAL: BLACK / WHITE */}
        <section className="sr" style={{position: 'relative', overflow: 'hidden', margin: 'clamp(24px,3vw,44px) 0 clamp(56px,6vw,88px)'}}>
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', minHeight: 'clamp(460px,60vw,640px)'}}>
            <div style={{background: '#12151C', display: 'flex', flexDirection: 'column', alignItems: 'flex-end', justifyContent: 'center', textAlign: 'right', padding: 'clamp(28px,5vw,64px) clamp(36px,6vw,88px)', gap: '20px'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.04em', lineHeight: '1.02', fontSize: 'clamp(28px,3.8vw,48px)', color: '#F3F4EE', margin: '0'}}>For <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>brands</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: 'clamp(14px,1.4vw,16px)', lineHeight: '1.6', color: '#9EA096', maxWidth: '340px', margin: '0'}}>Post offers, track responses, and see spend against every creator.</p>
              <a href="/brands" style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '13.5px', color: '#F3F4EE', background: 'transparent', border: '1.5px solid rgba(243,244,238,.4)', borderRadius: '999px', padding: '11px 22px', display: 'inline-flex', alignItems: 'center', gap: '6px', textDecoration: 'none'}}>Explore for brands <span aria-hidden="true">&rarr;</span></a>
            </div>
            <div style={{background: '#FFFFFF', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', justifyContent: 'center', textAlign: 'left', padding: 'clamp(28px,5vw,64px) clamp(36px,6vw,88px)', gap: '20px', border: '1.5px solid rgba(18,21,28,.14)'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.04em', lineHeight: '1.02', fontSize: 'clamp(28px,3.8vw,48px)', color: '#12151C', margin: '0'}}>For <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>creators</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: 'clamp(14px,1.4vw,16px)', lineHeight: '1.6', color: '#565C68', maxWidth: '340px', margin: '0'}}>Accept, counter, deliver, and get paid, without a single DM.</p>
              <a href="/creators" style={{fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '13.5px', color: '#12151C', background: 'transparent', border: '1.5px solid rgba(18,21,28,.3)', borderRadius: '999px', padding: '11px 22px', display: 'inline-flex', alignItems: 'center', gap: '6px', textDecoration: 'none'}}>Explore for creators <span aria-hidden="true">&rarr;</span></a>
            </div>
          </div>
          <div style={{position: 'absolute', left: '50%', top: 'clamp(28px,5vw,64px)', bottom: 'clamp(28px,5vw,64px)', width: '1px', background: 'var(--lime)', transform: 'translateX(-.5px)'}}></div>
          <div style={{position: 'absolute', left: '50%', bottom: 'clamp(22px,3.5vw,40px)', transform: 'translateX(-50%)', background: '#12151C', padding: '6px 18px', fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: 'clamp(17px,1.8vw,22px)', color: '#F3F4EE', whiteSpace: 'nowrap'}}>one deal room</div>
        </section>

  



        {/* ============ CREATOR SIDE SHOWCASE ============ */}
        {/* ============ GLASS PANEL SHOWCASE (Built for creators) ============ */}
        <section style={{position: 'relative', background: '#fff', padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)', overflow: 'hidden'}}>
          <div style={{position: 'relative', maxWidth: '1200px', margin: '0 auto', borderRadius: '32px', overflow: 'hidden', boxShadow: '0 20px 40px -30px rgba(40,45,25,.18)'}}>
            <img src="/landing/rectangle-84.webp" alt="Creator dashboard shown as glass panels, creator profile, opportunities, active deals, payment status" style={{width: '80%', height: 'auto', display: 'block', marginLeft: '-24px', filter: 'saturate(0.9) contrast(1.08) brightness(1.02)'}} decoding="async" loading="lazy" width={1800} height={1151} />
            <div aria-hidden="true" style={{position: 'absolute', top: '0', left: '0', width: '80%', height: '100%', background: 'linear-gradient(160deg,rgba(80,140,230,0.14),rgba(80,140,230,0.03) 60%)', mixBlendMode: 'multiply', pointerEvents: 'none'}}></div>
            <div aria-hidden="true" style={{position: 'absolute', top: '0', bottom: '0', right: '0', width: '46%', background: 'linear-gradient(to left,#fff 0%,#fff 55%,rgba(255,255,255,0) 100%)', pointerEvents: 'none'}}></div>
            <div style={{position: 'absolute', top: '50%', right: '6%', transform: 'translateY(-50%)', width: 'min(30%,360px)', minWidth: '220px', textAlign: 'left'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Built for you</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(30px,3.1vw,44px)', margin: '12px 0 0', color: '#12151C'}}>Your whole hustle, <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>organized.</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: '#565C68', margin: '16px 0 0', maxWidth: '30ch'}}>Your profile, open opportunities, active deals and payment status, all tracked in one dashboard, so nothing slips through DMs.</p>
            </div>
          </div>
        </section>

        {/* SCROLL EXPAND MASCOT */}
        <section id="expandSection" style={{position: 'relative', height: '220vh'}}>
          <div id="expandPin" style={{position: 'absolute', top: '0', left: '0', width: '100%', height: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', overflow: 'hidden'}}>
            <img id="bgImg" src="/landing/hero-outer-bg.webp" alt="" style={{position: 'absolute', inset: '0', width: '100%', height: '100%', objectFit: 'cover', willChange: 'opacity'}} decoding="async" />
            <img id="expandImg" src="/landing/hero-inner-mascot.webp" alt="guapd" style={{position: 'relative', zIndex: '1', borderRadius: '24px', boxShadow: '0 30px 70px -20px rgba(20,22,10,.35)', objectFit: 'cover', willChange: 'width,height'}} decoding="async" width={1254} height={1254} />
          </div>
        </section>


        {/* FOUR REASONS — single bounded container, spaced cards */}
        <section style={{padding: 'clamp(56px,6vw,88px) clamp(20px,5vw,72px)'}}>
        <div className="gx" style={{background: '#fff', border: '1px solid var(--hairline)', borderRadius: '36px', boxShadow: '0 40px 90px -50px rgba(40,45,25,.3)', padding: 'clamp(44px,5.5vw,72px) clamp(24px,4vw,48px)'}}>
          <div className="stack-head" style={{textAlign: 'center', margin: '0 auto clamp(44px,5.5vw,64px)'}}>
            <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>One connected system</span>
            <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.035em', lineHeight: '1.05', fontSize: 'clamp(30px,4vw,52px)', margin: '12px 0 0', color: 'var(--ink)'}}>Everything, <span className="t-accent" style={{fontSize: '1.05em'}}>in one place</span></h2>
          </div>
          <div className="stack-outer" style={{position: 'relative', height: '1900px', marginBottom: '70px'}}>
          <div className="stack-pin" style={{position: 'sticky', top: '232px', height: 'auto', overflow: 'visible'}}>

          {/* 01 — timeline that fills */}
          <div data-stack-card="0" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(135deg,#EFFAF5 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)'}}>
            <div>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)'}}>01</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>One thread</span></div>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0', maxWidth: '360px'}}>One thread, from offer to <span className="t-accent">payout</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '360px', margin: '16px 0 0'}}>Every deal moves through the same four steps, tracked automatically from the first offer to the final payout.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Auto-tracked</span>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>No manual updates</span>
              </div>
            </div>
            <div className="lift" style={{width: '100%'}}>
              <div style={{background: '#fff', borderRadius: '22px', border: '1px solid var(--hairline)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', padding: 'clamp(24px,3vw,28px)', display: 'flex', flexDirection: 'column', gap: '10px'}}>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#F3FBF6', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '600'}}><span>&#10003; Offer</span></span>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#F3FBF6', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '600'}}><span>&#10003; Agreed</span></span>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#F6FAFE', border: '1px solid var(--hairline)', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', fontWeight: '600', color: 'var(--ink-soft)'}}><span>&#8226; Delivered</span></span>
                <span style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '6px', background: '#fff', border: '1px dashed var(--hairline)', borderRadius: '999px', padding: '11px 18px', fontFamily: 'var(--font-ui)', fontSize: '13px', color: 'var(--ink-faint)'}}><span>Paid</span><span>&#8377;48,000</span></span>
              </div>
            </div>
          </div>

          </div>

          {/* 02 — split-flap board */}
          <div data-stack-card="1" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(225deg,#EFF6FD 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)'}}>
            <div style={{order: '1'}}>
              <div style={{padding: 'clamp(24px,3vw,32px)', display: 'flex', flexDirection: 'column', gap: '12px', background: '#fff', borderRadius: '20px', border: '1px solid var(--hairline)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}>
                <span className="t-meta" style={{color: 'var(--ink-faint)'}}>Deal &middot; #GD-2506</span>
                <div style={{height: '52px', overflow: 'hidden'}}>
                  <div style={{animation: 'flapRoll 9s ease-in-out infinite'}}>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '30px', color: 'var(--ink)'}}>Sent</div>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '30px', color: 'var(--ink)'}}>Countered</div>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '30px', color: 'var(--ink)'}}>Agreed</div>
                    <div style={{height: '52px', display: 'flex', alignItems: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '30px', color: 'var(--ink)'}}>Paid</div>
                  </div>
                </div>
                <div style={{display: 'flex', gap: '6px', marginTop: '6px'}}>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'var(--neon-deep)'}}></div>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'rgba(26,27,22,.14)', animation: 'stepLight2 9s ease-in-out infinite'}}></div>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'rgba(26,27,22,.14)', animation: 'stepLight3 9s ease-in-out infinite'}}></div>
                  <div style={{flex: '1', height: '5px', borderRadius: '3px', background: 'rgba(26,27,22,.14)', animation: 'stepLight4 9s ease-in-out infinite'}}></div>
                </div>
                <div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '26px', color: 'var(--ink)', marginTop: '10px'}}>&#8377;48,000</div>
              </div>
            </div>
            <div style={{order: '2'}}>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)'}}>02</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>Always current</span></div>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0', maxWidth: '340px'}}>Always know where things <span className="t-accent">stand</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '380px', margin: '16px 0 0'}}>No guessing, no chasing. Every state change is recorded the moment it happens.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Timestamped</span>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Always live</span>
              </div>
            </div>
          </div>

          </div>

          {/* 03 — flipping problem/fix tiles */}
          <div data-stack-card="2" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(135deg,#F5F0FD 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)', perspective: '1200px'}}>
            <div>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)'}}>03</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>Problem &rarr; fix</span></div>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0'}}>Three headaches, <span className="t-accent">gone</span>.</h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '340px', margin: '16px 0 0'}}>The three things brands and creators complain about most, solved by design.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Solved by design</span>
              </div>
            </div>
            <div style={{display: 'flex', flexDirection: 'column', gap: '12px'}}>
              <div style={{position: 'relative', height: '68px', transformStyle: 'preserve-3d', animation: 'flipTile 9s cubic-bezier(.6,0,.3,1) infinite'}}>
                <div style={{position: 'absolute', inset: '0', background: '#fff', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-faint)'}}>Problem</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Scattered DMs</span></div>
                <div style={{position: 'absolute', inset: '0', background: '#FBF8FE', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-soft)'}}>guapd</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>One deal inbox</span></div>
              </div>
              <div style={{position: 'relative', height: '68px', transformStyle: 'preserve-3d', animation: 'flipTile 9s cubic-bezier(.6,0,.3,1) .5s infinite'}}>
                <div style={{position: 'absolute', inset: '0', background: '#fff', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-faint)'}}>Problem</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Lost terms</span></div>
                <div style={{position: 'absolute', inset: '0', background: '#FBF8FE', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-soft)'}}>guapd</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Locked &amp; timestamped</span></div>
              </div>
              <div style={{position: 'relative', height: '68px', transformStyle: 'preserve-3d', animation: 'flipTile 9s cubic-bezier(.6,0,.3,1) 1s infinite'}}>
                <div style={{position: 'absolute', inset: '0', background: '#fff', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-faint)'}}>Problem</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Chasing payment</span></div>
                <div style={{position: 'absolute', inset: '0', background: '#FBF8FE', borderRadius: '14px', padding: '12px 16px', backfaceVisibility: 'hidden', transform: 'rotateY(180deg)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: '2px'}}><span className="t-meta" style={{color: 'var(--ink-soft)'}}>guapd</span><span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px', color: 'var(--ink)'}}>Live payout status</span></div>
              </div>
            </div>
          </div>

          </div>

          {/* 04 — card sorter */}
          <div data-stack-card="3" style={{position: 'absolute', left: '0', right: '0', top: '0', willChange: 'transform'}}>
          <div className="sr" style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 'clamp(28px,4vw,60px)', alignItems: 'center', background: 'linear-gradient(225deg,#FBFAEF 0%,#fff 60%)', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)', borderRadius: '28px', padding: 'clamp(28px,4vw,56px)', border: '1px solid rgba(18,21,28,.08)'}}>
            <div style={{position: 'relative', width: '100%', height: '270px', justifySelf: 'center', order: '1'}}>
              <div style={{position: 'absolute', left: '0', right: '0', top: '0', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) infinite'}}><span style={{fontWeight: '700'}}>Glow Labs</span><span style={{color: 'var(--ink-faint)'}}>&#8377;45,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '56px', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .12s infinite'}}><span style={{fontWeight: '700'}}>Move Athletics</span><span style={{color: 'var(--ink-faint)'}}>&#8377;60,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '112px', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .24s infinite'}}><span style={{fontWeight: '700'}}>Bawa Labs</span><span style={{color: 'var(--ink-faint)'}}>&#8377;35,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '168px', background: '#fff', borderRadius: '12px', padding: '12px 14px', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', display: 'flex', justifyContent: 'space-between', fontSize: '12px', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .36s infinite'}}><span style={{fontWeight: '700'}}>CRED</span><span style={{color: 'var(--ink-faint)'}}>&#8377;52,000</span></div>
              <div style={{position: 'absolute', left: '0', right: '0', top: '224px', background: '#FBFAEF', border: '1.5px solid var(--neon-deep)', boxShadow: '0 16px 34px -20px rgba(40,45,25,.3)', borderRadius: '12px', padding: '12px 14px', display: 'flex', justifyContent: 'space-between', fontSize: '12px', fontWeight: '700', color: 'var(--ink)', animation: 'snapIn 8s cubic-bezier(.34,1.5,.4,1) .48s infinite'}}><span>4 need you today</span><span style={{color: 'var(--ink)'}}>&rarr;</span></div>
            </div>
            <div style={{order: '2'}}>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '9px', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '5px 14px 5px 5px', boxShadow: '0 20px 44px -28px rgba(40,45,25,.16)'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '24px', height: '24px', borderRadius: '50%', background: 'var(--neon)', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)'}}>04</span><span className="t-meta" style={{color: 'var(--ink-soft)'}}>One queue</span></div>
              <h3 style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(26px,2.6vw,32px)', letterSpacing: '-0.03em', lineHeight: '1.22', margin: '14px 0 0', maxWidth: '340px'}}>Every deal, one <span className="t-accent">queue</span>.</h3>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.55', color: 'var(--ink-soft)', maxWidth: '380px', margin: '16px 0 0'}}>Every campaign lands in the same queue, ranked by what actually needs your attention today.</p>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '22px'}}>
                <span style={{display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: 'var(--font-ui)', fontSize: '12.5px', fontWeight: '600', color: 'var(--ink)', background: '#fff', border: '1px solid var(--frost-edge)', borderRadius: 'var(--radius-pill)', padding: '7px 13px'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#181C24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg>Ranked for you</span>
              </div>
            </div>
          </div>

          </div>
          </div>
          </div>
        </div>
        </section>

        {/* ============ APP SHOWCASE ============ */}
        <section style={{position: 'relative', width: '100vw', left: '50%', right: '50%', marginLeft: '-50vw', marginRight: '-50vw', overflow: 'hidden', marginTop: 'clamp(48px,6vw,88px)'}}>
          <img src="/landing/app-showcase-clouds.webp" alt="guapd deals dashboard with offer accepted, campaign live, deliverable approved, payment received, and earnings received notifications" style={{width: '100%', height: 'auto', display: 'block'}} decoding="async" loading="lazy" width={1800} height={1013} />
          <div style={{position: 'absolute', left: 'calc(clamp(20px,5vw,72px) + 120px)', top: '0', bottom: '0', width: '26%', display: 'flex', alignItems: 'center', justifyContent: 'flex-start', background: 'transparent'}}>
            <div style={{textAlign: 'left'}}>
              <span className="t-meta" style={{display: 'inline-block', color: 'var(--ink-faint)'}}>Your deals, your dashboard</span>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.04', fontSize: 'clamp(28px,3.8vw,48px)', margin: '12px 0 0', color: 'var(--ink)'}}>Everything, always in <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>view</span></h2>
              <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.5', color: 'var(--ink-soft)', margin: '14px 0 0', maxWidth: '320px'}}>Campaigns, earnings, and reviews, all live in one dashboard.</p>
              <div style={{marginTop: '24px'}}><div className="magnet"><a href="/signup/brand" className="lp-btn">Get early access</a></div></div>
            </div>
          </div>
        </section>

        {/* PRODUCT SHOWCASE */}
  

        {/* CAMPAIGNS */}
  




        {/* ============ FAQ ============ */}
        {/* CREATORS & BRANDS (borrowed from For Brands page) */}
  

        {/* BRANDS WE WORK WITH (borrowed from For Brands page) */}
  
  



        <section style={{padding: 'clamp(32px,4vw,52px) clamp(20px,5vw,72px)'}}>
          <div className="sr gx" style={{background: 'var(--card)', borderRadius: '28px', border: '1px solid var(--hairline)', boxShadow: '0 24px 54px -36px rgba(40,45,25,.24)', padding: 'clamp(40px,5.5vw,56px) clamp(28px,5vw,48px)'}}>
            <div style={{textAlign: 'center', marginBottom: 'clamp(28px,3.6vw,42px)'}}>
              <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.035em', lineHeight: '1.04', fontSize: 'clamp(28px,3.8vw,48px)', margin: '12px 0 0'}}>FAQ <span style={{fontFamily: '\'Instrument Serif\',serif', fontStyle: 'italic', fontWeight: '400'}}>answered</span></h2>
            </div>
            {faqs.map((f, i) => (
              <div className="faqitem" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} style={{display: 'grid', gridTemplateColumns: '56px 1fr 20px', borderTop: '1px solid var(--hairline)', padding: 'clamp(28px,3.4vw,36px) clamp(12px,1.6vw,18px)', borderRadius: '14px', cursor: 'pointer', transition: 'background .16s ease'}}>
                <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontSize: '26px', color: 'var(--ink-faint)', lineHeight: '1', alignSelf: 'baseline'}}>{f.num}</span>
                <div style={{gridColumn: '2'}}>
                  <span style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: 'clamp(16px,1.7vw,18px)', letterSpacing: '-0.01em'}}>{f.q}</span>
                  {f.open && (<>
                    <p style={{fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '12px 0 0', maxWidth: 'none'}}>{f.a}</p>
                  </>)}
                </div>
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="var(--ink-faint)" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink: '0', alignSelf: 'baseline'}}><path d={f.icon} /></svg>
              </div>
            ))}
          </div>
        </section>



        {/* VISION */}
        <section className="on-dark sr" style={{background: '#12151C', borderRadius: '28px', maxWidth: '1200px', margin: 'clamp(56px,6vw,88px) auto clamp(56px,6vw,88px)', padding: 'clamp(44px,5.5vw,64px) clamp(24px,4vw,44px)', textAlign: 'center'}}>
          <p style={{fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: 'clamp(19px,2vw,24px)', lineHeight: '1.5', letterSpacing: '-0.01em', margin: '0', color: '#F3F4EE'}}>Soon, agents handle the busywork, you stay in <span style={{fontFamily: '\'Instrument Serif\',serif', fontStyle: 'italic', fontWeight: '400', color: 'var(--lime)'}}>control</span>.</p>
          <a href="#" style={{display: 'inline-block', marginTop: '14px', fontFamily: 'var(--font-ui)', fontWeight: '600', fontSize: '13.5px', color: '#9EA096'}}>See the vision &rarr;</a>
        </section>

        {/* ============ CREATOR SIDE SHOWCASE ============ */}



        {/* CONVERGE — two sides meet */}
        <section id="cvSec" style={{position: 'relative', width: '100%', height: '230vh', overflow: 'hidden'}}>
          <div id="cvPin" style={{position: 'absolute', top: '0', left: '0', width: '100%', height: '100vh', overflow: 'hidden'}}>
            <div className="cv-motion" style={{position: 'absolute', inset: '0'}}>
              <div id="cvBarLeft" style={{position: 'absolute', left: '0', top: '50%', width: '50vw', height: '6px', borderRadius: '3px', background: '#E8FF66', transformOrigin: 'left center'}}></div>
              <div id="cvBarRight" style={{position: 'absolute', right: '0', top: '50%', width: '50vw', height: '6px', borderRadius: '3px', background: '#E8FF66', transformOrigin: 'right center'}}></div>
              <div id="cvCircle" style={{position: 'absolute', left: '50%', top: '50%', width: '120px', height: '120px', borderRadius: '50%', background: '#E8FF66', marginLeft: '-60px', marginTop: '-60px'}}></div>
              <div style={{position: 'absolute', inset: '0', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                <div style={{position: 'relative', zIndex: '2', maxWidth: '560px', textAlign: 'center', padding: '0 24px'}}>
                  <div id="cvEyebrow" style={{color: '#12151C', fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', letterSpacing: '.14em', opacity: '0'}}>TWO SIDES</div>
                  <h2 id="cvHead" style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(28px,3.8vw,48px)', margin: '16px 0 0', color: '#12151C', opacity: '0'}}>Get going. <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>Get guapd.</span></h2>
                  <p id="cvSub" style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.6', color: '#12151C', maxWidth: '560px', margin: '16px auto 0', opacity: '0'}}>One flow for briefs, terms and payouts, built for both sides of the deal.</p>
                  <button type="button" id="cvBtn" className="cv-cta" onClick={() => setDemoOpen(true)} style={{marginTop: '26px', display: 'inline-flex', opacity: '0'}}>
                    <span style={{display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'var(--ink)', border: 'none', color: '#FFFFFF', borderRadius: '999px', padding: '13px 26px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '14px'}}>Book demo</span>
                  </button>
                </div>
              </div>
            </div>
            <div className="cv-reduced" style={{display: 'none', position: 'absolute', inset: '0', alignItems: 'center', justifyContent: 'center'}}>
              <div style={{position: 'absolute', left: '50%', top: '50%', width: '120px', height: '120px', borderRadius: '50%', background: '#E8FF66', transform: 'translate(-50%,-50%) scale(30)'}}></div>
              <div style={{position: 'relative', zIndex: '2', maxWidth: '560px', textAlign: 'center', padding: '0 24px'}}>
                <div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '600', letterSpacing: '.14em', color: '#12151C'}}>TWO SIDES</div>
                <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.05', fontSize: 'clamp(28px,3.8vw,48px)', margin: '16px 0 0', color: '#12151C'}}>Get going. <span style={{fontFamily: 'var(--font-serif)', fontStyle: 'italic', fontWeight: '400'}}>Get guapd.</span></h2>
                <p style={{fontFamily: 'var(--font-ui)', fontSize: '15px', lineHeight: '1.6', color: '#12151C', maxWidth: '560px', margin: '16px auto 0'}}>One flow for briefs, terms and payouts, built for both sides of the deal.</p>
                <div style={{marginTop: '26px', display: 'inline-flex'}}>
                  <span style={{display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#FFFFFF', border: '1px solid #12151C', color: '#12151C', borderRadius: '999px', padding: '13px 26px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '14px'}}>Book demo</span>
                </div>
              </div>
            </div>
          </div>
        </section>

  

      </div>
      <BookDemoModal open={demoOpen} onClose={() => setDemoOpen(false)} />
    </div>
  )
}
