'use client'

import { useEffect } from 'react'

/**
 * For Brands, mobile layout — ported from the "GUAPD For Brands - Mobile"
 * export.
 *
 * Markup is generated by scripts/brands-mobile-convert-from-export.py — edit
 * the converter and re-run it, not the JSX below, or the next port silently
 * drops the change.
 *
 * A SEPARATE LAYOUT, not the desktop page reflowed, exactly as on /creators.
 * Both are in the DOM and brands-mobile.css picks one at 820px; `display: none`
 * keeps the hidden layout out of the accessibility tree, so a screen reader is
 * never read the page twice.
 *
 * Every heading is h2 or lower — the desktop layout owns the page's single h1,
 * and both are in the DOM.
 */
export default function BrandsMobileClient() {
  useEffect(() => {
    // Scroll progress, matching the landing and creators pages.
    const bar = document.getElementById('brandProgress')
    const onScroll = () => {
      if (!bar) return
      const d = document.documentElement
      const p = d.scrollTop / ((d.scrollHeight - d.clientHeight) || 1)
      bar.style.width = `${Math.min(100, Math.max(0, p * 100))}%`
    }
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    window.addEventListener('resize', onScroll)
    const stopScroll = () => {
      window.removeEventListener('scroll', onScroll)
      window.removeEventListener('resize', onScroll)
    }

    // Reveal on scroll. Elements are revealed rather than hidden if
    // IntersectionObserver is missing, so nothing can end up stuck invisible.
    const nodes = Array.from(document.querySelectorAll('.brands-mobile .sr'))
    if (!nodes.length) return stopScroll
    if (typeof IntersectionObserver === 'undefined') {
      nodes.forEach((n) => n.classList.add('sr-in'))
      return stopScroll
    }
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            e.target.classList.add('sr-in')
            io.unobserve(e.target)
          }
        })
      },
      { rootMargin: '0px 0px -12% 0px', threshold: 0.05 },
    )
    nodes.forEach((n) => io.observe(n))
    return () => { io.disconnect(); stopScroll() }
  }, [])

  return (
    <div className="brands-mobile">
      <div id="brandProgress" style={{position: 'fixed', top: '0', left: '0', height: '2px', width: '0%', background: 'var(--neon-deep)', zIndex: '200', transition: 'width .1s linear'}}></div>

      <div className="mobile-frame">
      <div style={{fontFamily: 'var(--font-ui)', color: 'var(--ink)', position: 'relative', overflowX: 'clip', background: '#fff'}}>

        {/* NAV */}
        <div style={{position: 'sticky', top: '0', zIndex: '100'}}>
    
        </div>

        {/* OPERATING SYSTEM (copy) */}
        <section className="sr hr" style={{padding: '56px 24px 32px', textAlign: 'center'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}><span style={{width: '5px', height: '5px', borderRadius: '50%', background: 'var(--ink)', flexShrink: '0'}}></span>Built for brands</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '30px', lineHeight: '1.2', margin: '20px 0 0', color: 'var(--ink)'}}>The operating system for <span className="opit">brand collabs.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '16px auto 0', maxWidth: '30ch'}}>One place for creators, approvals, deliverables, contracts and payments.</p>
        </section>
        <div style={{padding: '0 24px', marginTop: '32px', marginBottom: '56px'}}><img src="/brands-mobile/38e9e4ff.webp" alt="Brand team photo" style={{display: 'block', width: '100%', height: 'auto', borderRadius: '28px'}} width={720} height={900} decoding="async" loading="lazy" /></div>

        {/* DEAL BUILDER */}
        <section id="top" className="sr hr" style={{padding: '48px 24px 44px', marginTop: '28px', background: 'var(--ink)', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}>Deal builder</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '27px', lineHeight: '1.2', margin: '22px 0 0', color: '#fff'}}>Built for every stage<br />of a <span className="opit" style={{color: 'var(--neon)'}}>deal.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.65', color: '#B8BAB0', margin: '16px 0 0', maxWidth: '32ch'}}>Describe it once. We structure the brief, then track every deliverable and payment to close.</p>

          <div style={{position: 'relative', display: 'flex', alignItems: 'center', gap: '8px', border: '1px solid rgba(255,255,255,.18)', borderRadius: '14px', background: 'rgba(255,255,255,.06)', padding: '8px 8px 8px 14px', marginTop: '36px'}}>
            <div style={{flex: '1', position: 'relative', display: 'flex', alignItems: 'center', minHeight: '26px'}}>
              <textarea id="dealInput" rows={1} style={{width: '100%', border: 'none', outline: 'none', resize: 'none', background: 'transparent', fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.5', color: '#fff', position: 'relative', zIndex: '2', overflow: 'hidden', whiteSpace: 'nowrap'}}></textarea>
              <div id="dealGhost" aria-hidden="true" style={{position: 'absolute', left: '0', top: '50%', transform: 'translateY(-50%)', fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.5', color: '#C7C9BE', pointerEvents: 'none', zIndex: '1', whiteSpace: 'nowrap', overflow: 'hidden', maxWidth: '100%', opacity: '1'}}></div>
            </div>
            <button type="button" tabIndex={-1} aria-hidden="true" style={{background: 'var(--neon)', color: 'var(--ink)', border: 'none', borderRadius: '999px', padding: '9px 16px', fontFamily: 'var(--font-ui)', fontSize: '12px', fontWeight: '700', whiteSpace: 'nowrap'}}>Create</button>
          </div>

        </section>

        {/* VALUE TICKER */}
        <section className="sr hr" style={{padding: '24px 0'}}>
          <div style={{position: 'relative', overflow: 'hidden', WebkitMaskImage: 'linear-gradient(90deg,transparent,#000 9%,#000 91%,transparent)', maskImage: 'linear-gradient(90deg,transparent,#000 9%,#000 91%,transparent)'}}>
            <div style={{display: 'flex', width: 'max-content', gap: '10px', animation: 'mqMove 17s linear infinite', paddingRight: '10px'}}>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#7FA8E8'}}></span>locked terms</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#8FD4A8'}}></span>razorpay payouts</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#E8B36B'}}></span>full paper trail</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#E88F8F'}}></span>no whatsapp</span>
              <span style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#7FA8E8'}}></span>locked terms</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#8FD4A8'}}></span>razorpay payouts</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#E8B36B'}}></span>full paper trail</span>
              <span aria-hidden="true" style={{display: 'inline-flex', alignItems: 'center', gap: '7px', fontFamily: 'var(--font-ui)', fontSize: '9.5px', fontWeight: '500', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--ink-soft)', padding: '8px 0', whiteSpace: 'nowrap'}}>·</span>
            </div>
          </div>
        </section>

        {/* HERO */}
        <section className="sr sr" style={{padding: '28px 24px 40px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Platform</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.15', fontSize: '24px', margin: '18px 0 0', color: 'var(--ink)'}}>Everything, <span className="opit">in one place.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '14px', lineHeight: '1.65', color: 'var(--ink-soft)', margin: '16px 0 0', maxWidth: '32ch'}}>Plan campaigns, approve content and automate payments in one shared space.</p>
        </section>
        <div style={{padding: '0 24px'}}><img src="/brands-mobile/92a75f76.webp" alt="guapd glass panels showing campaign management, creator discovery, approvals and reporting" style={{width: '100%', aspectRatio: '1672/941', objectFit: 'contain', display: 'block', borderRadius: '16px'}} decoding="async" loading="lazy" /></div>

        {/* HOW IT WORKS */}
        <section className="sr sr" id="how" style={{padding: '56px 24px', marginTop: '48px', background: 'var(--ink)', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '7px 18px'}}>How it works</span>
          <div style={{marginTop: '20px', paddingTop: '24px', borderTop: '1px solid rgba(255,255,255,.16)', display: 'flex', gap: '16px'}}><span className="oavatar" style={{width: '26px', height: '26px', background: 'var(--neon)', color: 'var(--ink)', fontSize: '10.5px', flexShrink: '0'}}>01</span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>A structured brief in minutes</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#B8BAB0', margin: '8px 0 0'}}>Deliverables, budget, timeline, rights and payment, all agreed before work starts.</p></div></div>
          <div style={{paddingTop: '24px', marginTop: '24px', borderTop: '1px solid rgba(255,255,255,.16)', display: 'flex', gap: '16px'}}><span className="oavatar" style={{width: '26px', height: '26px', background: 'var(--neon)', color: 'var(--ink)', fontSize: '10.5px', flexShrink: '0'}}>02</span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>Agree on terms, on the record</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#B8BAB0', margin: '8px 0 0'}}>Every offer and counter is timestamped and locked. No disputes, no screenshots.</p></div></div>
          <div style={{paddingTop: '24px', marginTop: '24px', borderTop: '1px solid rgba(255,255,255,.16)', display: 'flex', gap: '16px'}}><span className="oavatar" style={{width: '26px', height: '26px', background: 'var(--neon)', color: 'var(--ink)', fontSize: '10.5px', flexShrink: '0'}}>03</span><div><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '16px'}}>See what's working, at a glance</div><p style={{fontFamily: 'var(--font-ui)', fontSize: '13px', lineHeight: '1.6', color: '#B8BAB0', margin: '8px 0 0'}}>Reach, engagement and spend across every creator, rolled up into one dashboard.</p></div></div>
        </section>

        {/* WHY BRANDS SWITCH */}
        <section className="sr hr" style={{padding: '56px 24px 32px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Why brands switch</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.22', fontSize: '24px', margin: '20px 0 0', color: 'var(--ink)'}}>All the reach of an agency.<br />None of the <span className="opit">retainer.</span></h2>
        </section>
        <div style={{padding: '0 24px'}}><img src="/brands-mobile/714edcea.webp" alt="Brand dashboard cards, active campaigns, applicants, contracts, payouts" style={{width: '100%', aspectRatio: '1402/1122', display: 'block'}} decoding="async" loading="lazy" /></div>
        <div style={{padding: '22px 24px 36px'}}>
          <div style={{borderRadius: '14px', overflow: 'hidden', border: '1px solid var(--hairline)'}}>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', background: '#fff'}}>
              <span style={{padding: '15px 16px', fontFamily: 'var(--font-ui)', fontWeight: '700', fontSize: '10.5px', letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--ink)'}}>What you get</span>
              <span style={{padding: '15px 8px', textAlign: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)', borderLeft: '1px solid var(--hairline)'}}>Guapd</span>
              <span style={{padding: '15px 8px', textAlign: 'center', fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '11px', color: 'var(--ink)', borderLeft: '1px solid var(--hairline)'}}>Agency</span>
            </div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', display: 'flex', alignItems: 'center', gap: '8px'}}>Talk to the creator, not a middleman</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#C7C9C0" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg></span></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', display: 'flex', alignItems: 'center', gap: '8px'}}>Terms in writing, agreed by both sides</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', display: 'flex', alignItems: 'center', gap: '8px'}}>No middleman knows what you pay</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#C7C9C0" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12" /></svg></span></div>
            <div style={{display: 'grid', gridTemplateColumns: '1fr 52px 52px', alignItems: 'center', borderTop: '1px solid var(--hairline)'}}><span style={{padding: '13px 16px', fontSize: '12px', color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', display: 'flex', alignItems: 'center', gap: '8px'}}>A whole campaign from one brief</span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span><span style={{padding: '13px 8px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderLeft: '1px solid var(--hairline)'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#4F6B12" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5" /></svg></span></div>
          </div>
        </div>
        {/* FEATURE LIST */}
        <section className="sr hr" style={{padding: '56px 24px', background: 'var(--ink)', color: '#fff'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>In one deal</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '23px', margin: '6px 0 0', color: '#fff'}}>No more WhatsApp, DMs and <span className="opit" style={{color: 'var(--neon)'}}>spreadsheets</span></h2>
          <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginTop: '32px'}}>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M14 3v4a1 1 0 0 0 1 1h4" /><path d="M5 21V5a2 2 0 0 1 2-2h7l5 5v13a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2Z" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Structured briefs</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Same format, every time</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m9 15 2 2 4-4" /><circle cx="12" cy="12" r="9" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Terms on record</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Locked on agreement</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" /><circle cx="12" cy="12" r="3" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Deliverable review</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Approve in one place</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="5" width="20" height="14" rx="2" /><line x1="2" y1="10" x2="22" y2="10" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Payment tracking</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Agreed to closed, live</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m17 2 4 4-4 4" /><path d="M3 11v-1a4 4 0 0 1 4-4h14" /><path d="m7 22-4-4 4-4" /><path d="M21 13v1a4 4 0 0 1-4 4H3" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Re-engagement</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>Re-run in one tap</div></div>
            <div style={{padding: '18px', border: '1px solid rgba(255,255,255,.14)', borderRadius: '14px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '10px', background: 'rgba(232,255,102,.12)', marginBottom: '14px'}}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--neon)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2" /></svg></span><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px'}}>Full deal timeline</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '11.5px', color: '#9EA096', marginTop: '5px'}}>One chronological record</div></div>
          </div>
        </section>
        {/* YOUR DATA */}
        <section id="privacySec" className="sr hr" style={{padding: '56px 24px'}}>
          <span className="opill" style={{fontSize: '10px', textTransform: 'uppercase', letterSpacing: '.07em', background: 'var(--neon)', color: 'var(--ink)', padding: '6px 16px'}}>Your data</span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', lineHeight: '1.2', fontSize: '23px', margin: '6px 0 0', color: 'var(--ink)'}}>As private as your <span className="opit">spreadsheet.</span></h2>
          <p style={{fontFamily: 'var(--font-ui)', fontSize: '13.5px', lineHeight: '1.6', color: 'var(--ink-2)', margin: '14px 0 0'}}>Your creator list, rates, spend and strategy stay yours. No other brand on guapd can see any of it.</p>
          <div style={{display: 'flex', flexDirection: 'column', gap: '12px', marginTop: '26px'}}>
            <div style={{display: 'flex', gap: '16px', alignItems: 'center', padding: '20px', border: '1px solid var(--hairline)', borderRadius: '16px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: '#E7F1FC', flexShrink: '0'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.6"><path d="M1.5 12S5 5.5 12 5.5 22.5 12 22.5 12 19 18.5 12 18.5 1.5 12 1.5 12Z" /><circle cx="12" cy="12" r="3" /></svg></span><div style={{flex: '1'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', color: 'var(--ink)'}}>Your campaign data</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', color: 'var(--ink-2)', marginTop: '3px'}}>Visible to your team only</div></div></div>
            <div style={{display: 'flex', gap: '16px', alignItems: 'center', padding: '20px', border: '1px solid var(--hairline)', borderRadius: '16px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: '#F0EAFD', flexShrink: '0'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.6"><circle cx="12" cy="12" r="9.5" /><line x1="5.4" y1="18.6" x2="18.6" y2="5.4" /></svg></span><div style={{flex: '1'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', color: 'var(--ink)'}}>Your competition</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', color: 'var(--ink-2)', marginTop: '3px'}}>Shut out completely</div></div></div>
            <div style={{display: 'flex', gap: '16px', alignItems: 'center', padding: '20px', border: '1px solid var(--hairline)', borderRadius: '16px'}}><span style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', borderRadius: '12px', background: '#FCF6E4', flexShrink: '0'}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#12151C" strokeWidth="1.6"><rect x="5" y="10.5" width="14" height="10" rx="2.4" /><path d="M8 10.5V7.2A4 4 0 0 1 16 7.2" /></svg></span><div style={{flex: '1'}}><div style={{fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '14px', color: 'var(--ink)'}}>Your rates and spend</div><div style={{fontFamily: 'var(--font-ui)', fontSize: '12px', color: 'var(--ink-2)', marginTop: '3px'}}>Never shown to another brand</div></div></div>
          </div>
        </section>

        {/* BRAND SIDE SHOWCASE */}
        <section className="sr hr" style={{padding: '52px 24px 0', textAlign: 'center'}}>
          <span style={{width: '6px', height: '6px', borderRadius: '50%', background: 'var(--neon-deep)', display: 'inline-block', marginBottom: '18px'}}></span>
          <h2 style={{fontFamily: 'var(--font-display)', fontWeight: '700', letterSpacing: '-0.03em', fontSize: '24px', lineHeight: '1.2', margin: '0', color: 'var(--ink)', whiteSpace: 'nowrap'}}>Contracts that <span className="opit">hold up.</span></h2>
        </section>
        <div style={{padding: '20px 24px 36px'}}><img src="/brands-mobile/5c79c248.webp" alt="Glass campaign overview dashboard" style={{width: '100%', aspectRatio: '1060/1484', display: 'block'}} decoding="async" loading="lazy" /></div>

        {/* CREATORS */}
  

        {/* BRANDS WE WORK WITH */}
  

        {/* TESTIMONIALS */}
  

  

      </div>
      </div>
    </div>
  )
}
